# In file `files_with_missing_metadata_2022-07-29` there are files which don't have metadata in their correspondent `json` file

In [1]:
l = []
file = "files_with_missing_metadata_2022-07-29.txt"
with open(file, 'r') as src:
    for f in src:
        line = f.rstrip()
        l.append(line)


In [2]:
l[0:10]

['/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/42d8aa3b49eb0d43954ed044ef58fdfc.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/fcf6407b5833c183baf810915b81b183.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/e3564578bbcc8314464a4248e5dede06.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/dfbabb8a28b8f234d88f6683f3da859b.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/4220711e3005214ddc83dee6d5d39c34.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/4dd2b2ee52388cc1aca233691beb3421.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/aa24ceb9fb6264f5c44bb3771315a831.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/a4e7684fc5c66c3a6d030e3

In [3]:
len(l)

102679

In [4]:
l[len(l)-1]

'/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible/5c0f93f5be5accea3b86c4bc94d7a5bb.WAV'

In [24]:
l = []
file = "files_with_missing_metadata_2022-07-29.txt"
with open(file, 'r') as src:
    for f in src:
        line = f.rstrip()
        substr = line.split("audios")[0]
        if "images_videos" not in substr:
            if substr not in l:
                l.append(substr)
        else:
            substr = line.split("images_videos")[0]
            if substr not in l:
                l.append(substr)


In [25]:
l

['/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/',
 '/LUSTRE/sa

**For the case of the dir with images let's see which files are not in `json`**

In [26]:
l = []
file = "files_with_missing_metadata_2022-07-29.txt"
with open(file, 'r') as src:
    for f in src:
        line = f.rstrip()
        substr = line.split("audios")[0]
        if "images_videos" in substr:
            l.append(substr)


In [27]:
l

['/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/ca811beabda05c07d7ce37209f45ac40_0008.JPG',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/15a3c8fa7a750ca6ada3792531a3dbf2_0004.JPG',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/74f3a15286d1f204e6019a7631d0f5a7_0002.JPG',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/1e20e16cbc5edbd7edb2f19d2f0c5083_0005.JPG',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/8eca12188c0b61969507741c9115d8a2_0001.JPG',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/0bc093f74bd086afc9ef9b728b374dda_0007.JPG']

**Let's check if this numbers are repeated**

In [33]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
ls "$d"|grep ".*_000[1-2].JPG"

74f3a15286d1f204e6019a7631d0f5a7_0002.JPG
8eca12188c0b61969507741c9115d8a2_0001.JPG
ce6f5df4a590edb30eaeb014e0c2ffd4_0001.JPG
e660334b7477becf3bb02b64135dd242_0002.JPG


In [34]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
ls "$d"|grep ".*_000[4-5].JPG"

15a3c8fa7a750ca6ada3792531a3dbf2_0004.JPG
1e20e16cbc5edbd7edb2f19d2f0c5083_0005.JPG
31422e4d11873d87648cd6a4c75f841d_0005.JPG
d8d6de82c7125a1e5998dbc5719bafb0_0004.JPG


In [35]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
ls "$d"|grep ".*_000[7-8].JPG"

0bc093f74bd086afc9ef9b728b374dda_0007.JPG
c0683990047847e14629668f6781e62e_0008.JPG
c564892ae2c4636620b77748fa18d7bb_0007.JPG
ca811beabda05c07d7ce37209f45ac40_0008.JPG


In [38]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
ls "$d"|grep ".*_0010.JPG"

0fb63870e55b1b72a60357ffeb1b74f1_0010.JPG


In [39]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
ls "$d"|grep ".*_0011.JPG"

cd3ef53bf41b698f987a0fd361ccc9c0_0011.JPG


In [42]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
ls "$d"|grep ".*_000[3,6,9].AVI"

11e1a01bdd48afd27ca3ab0257d0d962_0009.AVI
50737fa64600d499eb82fcffe373666c_0003.AVI
627b66600140fefb8a180e88a21fb722_0009.AVI
9c739b7c2ee9958db05e2fbd98fbe26f_0003.AVI
c686f7ee4fd5ae6698cd829aca0c705c_0006.AVI
ceeb56704fb126659c02bf798e5e5c14_0006.AVI


In [43]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
ls "$d"|grep ".*_0012.AVI"

1623a2e2f5967352817986d16674963e_0012.AVI


In [45]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
ls "$d"|grep ".*_000[3,6,9].mp4"

11e1a01bdd48afd27ca3ab0257d0d962_0009.mp4
50737fa64600d499eb82fcffe373666c_0003.mp4
627b66600140fefb8a180e88a21fb722_0009.mp4
9c739b7c2ee9958db05e2fbd98fbe26f_0003.mp4
c686f7ee4fd5ae6698cd829aca0c705c_0006.mp4
ceeb56704fb126659c02bf798e5e5c14_0006.mp4


In [46]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
ls "$d"|grep ".*_000[3,6,9].webm"

11e1a01bdd48afd27ca3ab0257d0d962_0009.webm
50737fa64600d499eb82fcffe373666c_0003.webm
627b66600140fefb8a180e88a21fb722_0009.webm
9c739b7c2ee9958db05e2fbd98fbe26f_0003.webm
c686f7ee4fd5ae6698cd829aca0c705c_0006.webm
ceeb56704fb126659c02bf798e5e5c14_0006.webm


**Let's review json**

In [47]:
%%bash
j="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/images_videos_simex_metadata_files_and_device_17-07-2022.json"
python3 -mjson.tool "$j"|head -n 80

{
    "DaysBetweenFirstAndLastDate": 35,
    "MetadataDevice": {
        "Make": "RECONYX",
        "Model": "HF2 PRO COVERT",
        "SerialNumber": "HLPXGM09049899",
        "NomenclatureNode": "1_33_1_1222",
        "CumulusName": "33",
        "CentroidCumulusLatitude": 17.57587,
        "CentroidCumulusLongitude": -100.64479,
        "DateDeployment": "2021-12-03",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.57516,
        "Longitude": -100.53432,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/120d7a479cedb659e94668fc8c8489a0_0049.JPG": {
            "Make": "RECONYX",
            "Model": "HF2 PRO COVERT",
            "DateTimeOriginal": "2021:12:06 20:51:50",
            "SerialNumber": "HLPXGM09049899",
            "FileSize": "241 kB",
            "ExifByteOrder": "Little-endian (Intel, II)",
            "ImageWidth": 2048,
          

In [50]:
%%bash
j="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/images_videos_simex_metadata_files_and_device_17-07-2022.json"
python3 -mjson.tool "$j"|tail -n 80

        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/c429c0c079b6a89a31055b6109d51fca_0108.AVI": {
            "BitRate": "5.2 Mbit/sec",
            "Endianness": "Little endian",
            "VideoBitsPerPixel": "24",
            "VideoCompression": "Motion JPEG DIB (fourcc:\"MJPG\")",
            "AudioSampleRate": "",
            "AudioCompressionRate": "",
            "AudioCompression": "",
            "AudioBitRate": "",
            "FileSize": "3.3 MB",
            "DateTimeOriginal": "2021:12:10 00:06:42",
            "BMPVersion": "Windows V3",
            "ImageWidth": 1024,
            "ImageHeight": 720,
            "Planes": 1,
            "ImageLength": 2211840,
            "PixelsPerMeterX": 0,
            "PixelsPerMeterY": 0,
            "NumColors": "Use BitDepth",
            "NumImportantColors": "All",
            "FrameRate": 12.5,
            "FrameCount": 64,
            "StreamCount": 1,
            "AudioSampleCount": -1

**Let's check if any image has correct coordinates**

In [49]:
%%bash
f="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/050560667eb6bae9d137fc657888c633_0406.JPG"
exiftool -a -j -n "$f"

[{
  "SourceFile": "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/050560667eb6bae9d137fc657888c633_0406.JPG",
  "ExifToolVersion": 12.43,
  "FileName": "050560667eb6bae9d137fc657888c633_0406.JPG",
  "Directory": "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos",
  "FileSize": 250896,
  "FileModifyDate": "2022:01:03 21:19:08-06:00",
  "FileAccessDate": "2022:08:02 12:17:27-05:00",
  "FileInodeChangeDate": "2022:08:01 19:53:58-05:00",
  "FilePermissions": 100777,
  "FileType": "JPEG",
  "FileTypeExtension": "JPG",
  "MIMEType": "image/jpeg",
  "ExifByteOrder": "II",
  "Make": "RECONYX",
  "Model": "HF2 PRO COVERT",
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": 2,
  "ModifyDate": "2022:01:03 21:19:09",
  "YCbCrPositioning": 2,
  "ExposureTime": 0.01666666667,
  "ISO": 200,
  "TimeZoneOffset": 0,
  "ExifVersion": "0220",
  "DateTimeOriginal": "2022:01:03 21:19:09",
  "CreateDate": "2022:01:03 21:19:09",

**It appear's the images have their coordinates masked...**

**Let's check coordinates of the images that have repeated number**

In [52]:
%%bash
f="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/8eca12188c0b61969507741c9115d8a2_0001.JPG"
exiftool -a -j -n "$f"

[{
  "SourceFile": "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/8eca12188c0b61969507741c9115d8a2_0001.JPG",
  "ExifToolVersion": 12.43,
  "FileName": "8eca12188c0b61969507741c9115d8a2_0001.JPG",
  "Directory": "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos",
  "FileSize": 292201,
  "FileModifyDate": "2021:12:03 19:02:06-06:00",
  "FileAccessDate": "2022:08:02 12:27:51-05:00",
  "FileInodeChangeDate": "2022:07:17 22:21:55-05:00",
  "FilePermissions": 100777,
  "FileType": "JPEG",
  "FileTypeExtension": "JPG",
  "MIMEType": "image/jpeg",
  "ExifByteOrder": "II",
  "Make": "RECONYX",
  "Model": "HF2 PRO COVERT",
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": 2,
  "ModifyDate": "2021:12:03 19:02:07",
  "YCbCrPositioning": 2,
  "ExposureTime": 0.03333333333,
  "ISO": 400,
  "ExifVersion": "0220",
  "DateTimeOriginal": "2021:12:03 19:02:07",
  "CreateDate": "2021:12:03 19:02:07",
  "TimeZoneOffset": 0,

In [53]:
%%bash
f="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/ce6f5df4a590edb30eaeb014e0c2ffd4_0001.JPG"
exiftool -a -j -n "$f"

[{
  "SourceFile": "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/ce6f5df4a590edb30eaeb014e0c2ffd4_0001.JPG",
  "ExifToolVersion": 12.43,
  "FileName": "ce6f5df4a590edb30eaeb014e0c2ffd4_0001.JPG",
  "Directory": "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos",
  "FileSize": 729220,
  "FileModifyDate": "2021:12:05 11:40:10-06:00",
  "FileAccessDate": "2022:08:01 19:53:08-05:00",
  "FileInodeChangeDate": "2022:08:01 19:53:08-05:00",
  "FilePermissions": 100777,
  "FileType": "JPEG",
  "FileTypeExtension": "JPG",
  "MIMEType": "image/jpeg",
  "ExifByteOrder": "II",
  "Make": "RECONYX",
  "Model": "HF2 PRO COVERT",
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": 2,
  "ModifyDate": "2021:12:05 11:40:11",
  "YCbCrPositioning": 2,
  "ExposureTime": 0.02677083333,
  "ISO": 400,
  "TimeZoneOffset": 0,
  "ExifVersion": "0220",
  "DateTimeOriginal": "2021:12:05 11:40:11",
  "CreateDate": "2021:12:05 11:40:11",

**Another images**

In [54]:
%%bash
f="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/74f3a15286d1f204e6019a7631d0f5a7_0002.JPG"
exiftool -a -j -n "$f"

[{
  "SourceFile": "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/74f3a15286d1f204e6019a7631d0f5a7_0002.JPG",
  "ExifToolVersion": 12.43,
  "FileName": "74f3a15286d1f204e6019a7631d0f5a7_0002.JPG",
  "Directory": "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos",
  "FileSize": 291208,
  "FileModifyDate": "2021:12:03 19:02:08-06:00",
  "FileAccessDate": "2022:07:17 22:21:55-05:00",
  "FileInodeChangeDate": "2022:07:17 22:21:55-05:00",
  "FilePermissions": 100777,
  "FileType": "JPEG",
  "FileTypeExtension": "JPG",
  "MIMEType": "image/jpeg",
  "ExifByteOrder": "II",
  "Make": "RECONYX",
  "Model": "HF2 PRO COVERT",
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": 2,
  "ModifyDate": "2021:12:03 19:02:08",
  "YCbCrPositioning": 2,
  "ExposureTime": 0.03333333333,
  "ISO": 400,
  "ExifVersion": "0220",
  "DateTimeOriginal": "2021:12:03 19:02:08",
  "CreateDate": "2021:12:03 19:02:08",
  "TimeZoneOffset": 0,

In [55]:
%%bash
f="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/e660334b7477becf3bb02b64135dd242_0002.JPG"
exiftool -a -j -n "$f"

[{
  "SourceFile": "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/e660334b7477becf3bb02b64135dd242_0002.JPG",
  "ExifToolVersion": 12.43,
  "FileName": "e660334b7477becf3bb02b64135dd242_0002.JPG",
  "Directory": "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos",
  "FileSize": 663833,
  "FileModifyDate": "2021:12:05 11:40:12-06:00",
  "FileAccessDate": "2022:08:01 19:52:23-05:00",
  "FileInodeChangeDate": "2022:08:01 19:52:23-05:00",
  "FilePermissions": 100777,
  "FileType": "JPEG",
  "FileTypeExtension": "JPG",
  "MIMEType": "image/jpeg",
  "ExifByteOrder": "II",
  "Make": "RECONYX",
  "Model": "HF2 PRO COVERT",
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": 2,
  "ModifyDate": "2021:12:05 11:40:12",
  "YCbCrPositioning": 2,
  "ExposureTime": 0.02677083333,
  "ISO": 400,
  "TimeZoneOffset": 0,
  "ExifVersion": "0220",
  "DateTimeOriginal": "2021:12:05 11:40:12",
  "CreateDate": "2021:12:05 11:40:12",

**Manually reviewing the images, next are the ones that need to be moved**

In [63]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
dst="/LUSTRE/sacmod/SIPECAM/sipecam_files_simex_error"
mv "$d/ce6f5df4a590edb30eaeb014e0c2ffd4_0001.JPG" "$dst/"
mv "$d/d8d6de82c7125a1e5998dbc5719bafb0_0004.JPG" "$dst/"
mv "$d/31422e4d11873d87648cd6a4c75f841d_0005.JPG" "$dst/"
mv "$d/c564892ae2c4636620b77748fa18d7bb_0007.JPG" "$dst/"
mv "$d/c0683990047847e14629668f6781e62e_0008.JPG" "$dst/"

**Manually reviewing the videos, next are the ones that need to be moved**

In [67]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
dst="/LUSTRE/sacmod/SIPECAM/sipecam_files_simex_error"
mv "$d/9c739b7c2ee9958db05e2fbd98fbe26f_0003.mp4" "$dst/"
mv "$d/9c739b7c2ee9958db05e2fbd98fbe26f_0003.AVI" "$dst/"
mv "$d/9c739b7c2ee9958db05e2fbd98fbe26f_0003.webm" "$dst/"
mv "$d/ceeb56704fb126659c02bf798e5e5c14_0006.mp4" "$dst/"
mv "$d/ceeb56704fb126659c02bf798e5e5c14_0006.AVI" "$dst/"
mv "$d/ceeb56704fb126659c02bf798e5e5c14_0006.webm" "$dst/"
mv "$d/627b66600140fefb8a180e88a21fb722_0009.mp4" "$dst/"
mv "$d/627b66600140fefb8a180e88a21fb722_0009.webm" "$dst/"
mv "$d/627b66600140fefb8a180e88a21fb722_0009.AVI" "$dst/"

**Reviewing manually the images, it seems that the coordinates that must be in json are:**


```
    "MetadataDevice": {
        "Make": "RECONYX",
        "Model": "HF2 PRO COVERT",
        "SerialNumber": "HLPXGM09049899",
        "NomenclatureNode": "1_33_1_1222",
        "CumulusName": "33",
        "CentroidCumulusLatitude": 17.57587,
        "CentroidCumulusLongitude": -100.64479,
        "DateDeployment": "2021-12-03",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.5751,
        "Longitude": -100.5342,
        "NodeCategoryIntegrity": "Integro"
    }
```

**Hardcoding code of `extract`cli with last info...**

**extract**

In [72]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/"
#if number_of_processes is passed as arg then is assumed will execute in parallel
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [75]:
%%bash
f="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/images_videos_simex_metadata_files_and_device_03-08-2022.json"
python3 -mjson.tool "$f"|head -n 80

{
    "MetadataDevice": {
        "Make": "RECONYX",
        "Model": "HF2 PRO COVERT",
        "SerialNumber": "HLPXGM09049899",
        "NomenclatureNode": "1_33_1_1222",
        "CumulusName": "33",
        "CentroidCumulusLatitude": 17.57587,
        "CentroidCumulusLongitude": -100.64479,
        "DateDeployment": "2021-12-03",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.5751,
        "Longitude": -100.5342,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/fabb0f21925f38252cf722f3bf30a876_0290.JPG": {
            "Make": "RECONYX",
            "Model": "HF2 PRO COVERT",
            "DateTimeOriginal": "2021:12:30 18:22:26",
            "SerialNumber": "HLPXGM09049899",
            "FileSize": "251 kB",
            "ExifByteOrder": "Little-endian (Intel, II)",
            "ImageWidth": 2048,
            "ImageHeight": 1440,
            "Encod

In [76]:
%%bash
f="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos/images_videos_simex_metadata_files_and_device_03-08-2022.json"
python3 -mjson.tool "$f"|tail -n 80

            "AudioSampleRate": "",
            "AudioCompressionRate": "",
            "AudioCompression": "",
            "AudioBitRate": "",
            "FileSize": "3.5 MB",
            "DateTimeOriginal": "2021:12:13 01:45:24",
            "BMPVersion": "Windows V3",
            "ImageWidth": 1024,
            "ImageHeight": 720,
            "Planes": 1,
            "ImageLength": 2211840,
            "PixelsPerMeterX": 0,
            "PixelsPerMeterY": 0,
            "NumColors": "Use BitDepth",
            "NumImportantColors": "All",
            "FrameRate": 12.5,
            "FrameCount": 64,
            "StreamCount": 1,
            "AudioSampleCount": -1,
            "Encoding": "",
            "NumChannels": -1,
            "AvgBytesPerSec": -1,
            "BitsPerSample": -1,
            "Duration": "5.12 s",
            "MaxDataRate": 26542080,
            "Megapixels": 0.73728,
            "GPSLatitudeRef": "North",
            "GPSLongitudeRef": "West",
            "GPS

# We found that a video was wrong

`/LUSTRE/sacmod/SIPECAM/data/99/4_99_0_1583/HLPXGM09049534/2022-02-04/images_videos/71a5acd4de1924efc5ed740f6ad3c055_1044.AVI`

**Will be moved**

In [8]:
%%bash
f="/LUSTRE/sacmod/SIPECAM/data/99/4_99_0_1583/HLPXGM09049534/2022-02-04/images_videos/71a5acd4de1924efc5ed740f6ad3c055_1044.AVI"
dst="/LUSTRE/sacmod/SIPECAM/sipecam_files_simex_error"
mv "$f" "$dst/"

**And this video wasn't in the `json`..., then will not rerun extract cli**

## For the case of audios

In [1]:
%%bash
f="/shared_volume/dirs_audio_with_missing_metadata_2022-07-29.txt"
echo '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/' > "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/' >> "$f"
echo '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/' >> "$f"


In [2]:
%%bash
cat "/shared_volume/dirs_audio_with_missing_metadata_2022-07-29.txt"

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022

In [5]:
%%bash
f="/shared_volume/dirs_audio_with_missing_metadata_2022-07-29.txt"
for dir_to_be_processed in $(cat "$f");do
    json=$(find "$dir_to_be_processed" -name "*.json")
    echo "$json"
    python3 -mjson.tool "$json"|head -n 50
    echo "-------------------------"
done

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 29,
    "MetadataDevice": {
        "Artist": "AudioMoth 248D9B0260371FD2",
        "SerialNumber": "248D9B0260371FD2",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.46268,
        "Longitude": -100.19501,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/4644f4c89d836f4aeef0527b7e262b55.wav": {
            "Battery": "4.6V",
            "Datetime": "20:40:00 25/02/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768

usage: python -m json.tool [-h] [--sort-keys] [--json-lines]
                           [infile] [outfile]
python -m json.tool: error: argument infile: can't open '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/Audible_simex_metadata_files_and_device_18-07-2022.json
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json': [Errno 2] No such file or directory: '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/Audible_simex_metadata_files_and_device_18-07-2022.json\n/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json'


-------------------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 12,
    "MetadataDevice": {
        "Artist": "AudioMoth 248D9B0260371F78",
        "SerialNumber": "248D9B0260371F78",
        "NomenclatureNode": "1_33_1_1222",
        "CumulusName": "33",
        "CentroidCumulusLatitude": 17.57587,
        "CentroidCumulusLongitude": -100.64479,
        "DateDeployment": "2021-12-04",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.57816,
        "Longitude": -100.51826,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/audios/Audible/950cca88199119badf5727ee44845200.wav": {
            "Battery": "4.1V",
            "Datetime": "15:20:00 16/12/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
 

In [6]:
%%bash
python3 -mjson.tool "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/Audible_simex_metadata_files_and_device_18-07-2022.json"|head -n 50

{
    "DaysBetweenFirstAndLastDate": 9,
    "MetadataDevice": {
        "Artist": "AudioMoth 24E1440360374A34",
        "SerialNumber": "24E1440360374A34",
        "NomenclatureNode": "1_33_0_1224",
        "CumulusName": "33",
        "CentroidCumulusLatitude": 17.57587,
        "CentroidCumulusLongitude": -100.64479,
        "DateDeployment": "2022-01-10",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.54693,
        "Longitude": -100.63046,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/3abb27544a93ee745d68ff74accc48a4.WAV": {
            "Battery": "3.3V",
            "Datetime": "15:30:00 13/01/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.0 Kbit/sec",
            "SerialNumber": "24E1440360374A34",
            "FileSize": "5.8 MB",
            "Encoding": "Microsoft PCM",
    

In [7]:
%%bash
python3 -mjson.tool "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json"|head -n 50

{
    "DaysBetweenFirstAndLastDate": 141,
    "MetadataDevice": {
        "Artist": "AudioMoth 24E1440360374A34",
        "SerialNumber": "24E1440360374A34",
        "NomenclatureNode": "1_33_0_1224",
        "CumulusName": "33",
        "CentroidCumulusLatitude": 17.57587,
        "CentroidCumulusLongitude": -100.64479,
        "DateDeployment": "2022-01-10",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.54693,
        "Longitude": -100.63046,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/7b0bc5520a566b03fd368964a3a16564.wav": {
            "Battery": "3.2V",
            "Datetime": "21:00:00 24/04/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.0 Kbit/sec",
            "SerialNumber": "24E1440360374A34",
            "FileSize": "5.8 MB",
            "Encoding": "Microsoft PCM",
  

**Lets check if there are repeated files in each of the dirs**

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
file="/shared_volume/dirs_audio_with_missing_metadata_2022-07-29.txt"

In [3]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [4]:
patterns = ["WAV", "wav"]

In [5]:
with open(file, 'r') as src:
    dictionary = {}
    dirs = src.read().splitlines()
    for d in dirs:
        iterable = multiple_file_types(d,patterns, recursive=True)
        dictionary[d] = {}
        dictionary[d]["not_repeated"] = []
        dictionary[d]["repeated"] = []
        l2 = dictionary[d]["not_repeated"]
        l3 = dictionary[d]["repeated"]
        l2_check = []
        l3_check = []
        for audio_file in iterable:
            audio_file_pathlib = pathlib.Path(audio_file)
            audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
            #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
            if audio_file_no_suffix not in l2_check:
                l2_check.append(audio_file_no_suffix)
                l2.append(audio_file)
            else:
                l3_check.append(audio_file_no_suffix)
                l3.append(audio_file)

   

In [6]:
dirs

['/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/',
 '/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/',
 '/LUSTRE/sa

In [7]:
l_1_repeated = dictionary['/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/']["repeated"]

In [8]:
len(l_1_repeated)

1173

In [9]:
l_1_not_repeated = dictionary['/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/']["not_repeated"]

In [10]:
len(l_1_not_repeated)

3872

In [11]:
l_1_repeated[0:10]

['/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/42d8aa3b49eb0d43954ed044ef58fdfc.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/fcf6407b5833c183baf810915b81b183.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/cf56c803a3698677e815824094015086.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/4220711e3005214ddc83dee6d5d39c34.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/518eddf0cea44802260d79bd851cc5e6.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/aa24ceb9fb6264f5c44bb3771315a831.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/f03250ce70e35967643025e18876909d.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/54b2d2f485390e5e56c5831

In [12]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/"
ls "$d"|grep "42d8aa3b49eb0d43954ed044ef58fdfc"

42d8aa3b49eb0d43954ed044ef58fdfc.WAV
42d8aa3b49eb0d43954ed044ef58fdfc.wav


**Checking that are the same audio**

In [14]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/"
cp "$d/42d8aa3b49eb0d43954ed044ef58fdfc.WAV" .
cp "$d/42d8aa3b49eb0d43954ed044ef58fdfc.wav" .

**Checking which dirs have repeated files and how many files are repeated**

In [13]:
for d in dirs:
    print(d)
    print(len(dictionary[d]["repeated"]))
    print("-"*40)

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/
1173
----------------------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/
0
----------------------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/
0
----------------------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/
0
----------------------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/
0
----------------------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/
0
----------------------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/
0
----------------------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/
0
----------------------------------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/
0
---

In [26]:
%%bash
cat /shared_volume/dirs_audio_with_missing_metadata_2022-07-29.txt

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022

# It was implemented a cli to check if a dir have different serial numbers of files as this situation was detected...

**For each dir check if files have different serial numbers and move files inside a dir**

In [15]:
%%bash
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/audios/Ultrasonico/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/audios/Ultrasonico/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible/" >> /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt

In [16]:
%%bash
cat /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/audios/Ultrasonico/
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico/
/LUSTRE/sacmod/SIPECAM/data/33/

In [18]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt)
    do echo "$dir_to_be_processed"
    s_n_r=$(echo "$dir_to_be_processed"|cut -d'/' -f8)
    echo "$s_n_r"
    check_if_files_in_dir_are_from_different_serial_numbers_and_move_them --input_directory "$dir_to_be_processed" --serial_number_reference "$s_n_r" --number_of_processes 10
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/
248D9B0260371FD2
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/
24E1440360372FF8
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/
24F3190160371FAB
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/
24F3190160371FAB
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/
248D9B0260371FD2
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/
24F31901603734A9
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible/
24E1440360371ED3
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/
242A260460373575
----------------
/LUSTRE/sacmod/SIPECAM/data/

**Check which dirs were created**

In [21]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for d in $(cat /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt)
    do echo "$d"
    find "$d" -type d -name '*[0-9]*'
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B0260371F39
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B026037BD85
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F31901603734A9
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F3190160371F6C
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24E1440360371ED3
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/242A260460373575
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24F3190160371FAB
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24

In [26]:
%%bash
ls /LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B0260371F39/*.wav|wc -l
ls /LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B026037BD85/*.wav|wc -l
ls /LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F31901603734A9/*.wav|wc -l
ls /LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F3190160371F6C/*.wav|wc -l

989
165
348
324


In [27]:
989+165+348+324

1826

**Move dirs that have serial number different from the std dir**

In [28]:
%%bash
mkdir -p /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/

In [29]:
%%bash
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B0260371F39" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B026037BD85" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F31901603734A9" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F3190160371F6C" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24E1440360371ED3" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/242A260460373575" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24F3190160371FAB" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24F3190160371F6C" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/242A260460373575" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/24E1440360372FF8" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/24F3190160374A1B" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/24E1440360371ED3" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/242A260460373575" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/24E1440360371F6C" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/248D9B0260371F39" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/248D9B026037BD85" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/24F3190160371F6C" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/24E1440360371F6C" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/248D9B0260371FD2" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/248D9B0260371F39" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/248D9B026037BD85" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/24F3190160371F6C" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible/248C7D075B1F35B9" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible/24F3190160374A1B" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible/242A260460373575" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible/24E1440360372FF8" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible/24F3190160371FAB" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/248C7D075B1F35B9" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/24F3190160374A1B" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/24E1440360371ED3" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/24E1440360372FF8" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/24F3190160371FAB" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible/24F3190160371ED3" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible/24F3190160377B16" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible/248D9B0260377D10" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/audios/Ultrasonico/24F3190160371ED3" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/audios/Ultrasonico/24E1440360374A34" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/audios/Ultrasonico/248D9B0260377D10" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico/24F3190160371ED3" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico/24E1440360374A34" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico/24F3190160377B16" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/audios/Ultrasonico/248D9B0260371F78" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/audios/Ultrasonico/24F31901603749F6" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/audios/Ultrasonico/24F3190160371F6C" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/audios/Ultrasonico/248D9B0260372F15" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible/24F3190160377B48" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible/24F31901603749F6" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible/24F3190160377B16" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible/24E1440360372FF8" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible/248D9B0260372F15" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/24F3190160371ED3" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/24F3190160374A1B" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/24F3190160377B16" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/248D9B0260377D10" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/24F3190160371FAB" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/audios/Audible/24F3190160377B48" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/audios/Audible/24F31901603749F6" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/audios/Audible/248D9B0260372F15" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible/24F3190160377B48" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible/248D9B0260371F78" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible/24F31901603749F6" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible/24F3190160371F6C" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible/248D9B0260371EA1" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible/24F3190160371ED3" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible/24E1440360374A34" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible/242A2604603734A9" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible/248D9B0260377D10" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt

In [30]:
%%bash
cat /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B0260371F39
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B026037BD85
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F31901603734A9
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F3190160371F6C
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24E1440360371ED3
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/242A260460373575
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24F3190160371FAB
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24F3190160371F6C
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/242A260460373575
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/au

**(this solution was not good, see down for a better solution) Move to dir: /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/**

In [33]:
%%bash
txt="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt"
dst_dir="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/"
for d in $(cat "$txt")
    do
        mv "$d" "$dst_dir"
done

mv: cannot move '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24F3190160371F6C' to '/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/24F3190160371F6C': Directory not empty
mv: cannot move '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/242A260460373575' to '/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/242A260460373575': Directory not empty
mv: cannot move '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/24E1440360371ED3' to '/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/24E1440360371ED3': Directory not empty
mv: cannot move '/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/242A260460373575' to '/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/242A260460373575': Directory not empty
mv: cann

CalledProcessError: Command 'b'txt="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt"\ndst_dir="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/"\nfor d in $(cat "$txt")\n    do\n        mv "$d" "$dst_dir"\ndone\n'' returned non-zero exit status 1.

**Check**

In [34]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for d in $(cat /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt)
    do echo "$d"
    find "$d" -type d -name '*[0-9]*'
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24F3190160371F6C
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/242A260460373575
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/24E1440360371ED3
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/242A260460373575
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ult

**Is better next solution of Move to dir: /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/**

In [1]:
%%bash
txt="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt"
dst_dir="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/"
for d in $(cat "$txt")
    do
        serial_number=$(echo $d|cut -d'/' -f8)
        for f in $(ls "$d")
            do
                mkdir -p "$dst_dir$serial_number"
                mv "$d/$f" "$dst_dir$serial_number"
            done
done

ls: cannot access '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B0260371F39': No such file or directory
ls: cannot access '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B026037BD85': No such file or directory
ls: cannot access '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F31901603734A9': No such file or directory
ls: cannot access '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F3190160371F6C': No such file or directory
ls: cannot access '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24E1440360371ED3': No such file or directory
ls: cannot access '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/242A260460373575': No such file or directory
ls: cannot access '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Aud

**Check if there are no wavs files**

In [13]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for d in $(cat /shared_volume/complete_dirs_audio_with_missing_metadata_2022-07-29.txt)
    do
    dirs_with_diff_serial_number=$(find "$d" -type d -name '*[0-9]*')
    for dir_diff in $dirs_with_diff_serial_number
        do
            echo "$dir_diff"
            ls "$dir_diff"
        done
    echo "----------------"
done
IFS=$SAVEIFS

----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24F3190160371F6C
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/242A260460373575
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/24E1440360371ED3
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/242A260460373575
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/248D9B0260371F39
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/248D9B026037BD85
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/24F3190160371F6C
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/24E1440360371F6C
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/A

**Delete dirs with different serial numbers**

In [18]:
%%bash
txt="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/05-08-2022/list_dirs_different_serial_number.txt"
for d in $(cat "$txt")
    do
        echo "$d"
        rm -rf "$d"
done

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B0260371F39
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/248D9B026037BD85
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F31901603734A9
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/24F3190160371F6C
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24E1440360371ED3
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/242A260460373575
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24F3190160371FAB
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/24F3190160371F6C
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/242A260460373575
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/au

## For serial number: 248D9B0260371FD2

**Which json is the one related to this json? use json of `extract`cli**

In [40]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_15-07-2022_cumulus_31.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    json=$(find "$dir_to_be_processed" -name "*extract*json")
    echo "$json"
    python3 -mjson.tool "$json"|grep '248D9B0260371FD2' | head -n 5
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/cumulo_31/entrega_09.junio.2022/Nodo-31-Atoyac/Audiomoth-1-31-0-1218-los valles/10306795/10306795_simex_extract_serial_numbers_dates_and_metadata_of_files_and_device.json
        "Artist": "AudioMoth 248D9B0260371FD2",
        "SerialNumber": "248D9B0260371FD2"
            "SerialNumber": "248D9B0260371FD2",
            "Comment": "Recorded at 20:40:00 19/12/2021 (UTC-6) by AudioMoth 248D9B0260371FD2 at medium gain setting while battery state was 4.4V and temperature was 23.3C.",
            "SerialNumber": "248D9B0260371FD2",
----------------------------
/LUSTRE/sacmod/SIPECAM/cumulo_31/entrega_09.junio.2022/Nodo-31-Atoyac/Audiomoth-1-31-0-1218-los valles/10306520/10306520_simex_extract_serial_numbers_dates_and_metadata_of_files_and_device.json
----------------------------
/LUSTRE/sacmod/SIPECAM/cumulo_31/entrega_09.junio.2022/Nodo-31-Atoyac/Audiomoth-1-31-0-1218-los valles/10305652/10305652_simex_extract_serial_numbers_dates_and_metadata_of_files_and_device.jso

In [39]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_18-07-2022_cumulus_31_33.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    echo "$dir_to_be_processed"
    json=$(find "$dir_to_be_processed" -maxdepth 1 -name "*extract*json")
    echo "$json"
    python3 -mjson.tool "$json"|grep '248D9B0260371FD2' | head -n 5
    echo "-----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/Lost1611644_simex_extract_serial_numbers_dates_and_metadata_of_files_and_device.json
-----------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4283135
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4283135/Lost4283135_simex_extract_serial_numbers_dates_and_metadata_of_files_and_device.json
-----------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4033497
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4033497/Lost4033497_simex_extract_serial_numbers_dates_and_metadata_of_files_and_device.json
-----------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_

**Check logs of `move`cli**

In [47]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_15-07-2022_cumulus_31.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    logs=$(find "$dir_to_be_processed" -name "logs_simex_move_files*.logs")
    echo "$logs"
    var=$(cat "$logs"|grep '248D9B0260371FD2' | head -n 1)
    if [ -z "$var" ]
    then
          echo "serial number not found"
    else
          cat "$logs"|head -n 50
    fi
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/cumulo_31/entrega_09.junio.2022/Nodo-31-Atoyac/Audiomoth-1-31-0-1218-los valles/10306795/logs_simex_move_files_to_standard_directory.logs
2022-07-17 08:20:05,822 [INFO]  Dir /LUSTRE/sacmod/SIPECAM/cumulo_31/entrega_09.junio.2022/Nodo-31-Atoyac/Audiomoth-1-31-0-1218-los valles/10306795 has serial number 248D9B0260371FD2
2022-07-17 08:20:05,824 [INFO]  File /LUSTRE/sacmod/SIPECAM/cumulo_31/entrega_09.junio.2022/Nodo-31-Atoyac/Audiomoth-1-31-0-1218-los valles/10306795/20211208_212000.WAV has date 2021-12-08
2022-07-17 08:20:05,824 [INFO]  File /LUSTRE/sacmod/SIPECAM/cumulo_31/entrega_09.junio.2022/Nodo-31-Atoyac/Audiomoth-1-31-0-1218-los valles/10306795/20220114_022000.WAV has date 2022-01-14
2022-07-17 08:20:05,824 [INFO]  DaysBetweenFirstAndLastDate: 37
2022-07-17 08:20:06,124 [INFO]  Query to Zendro GQL: query {
  physical_devices(pagination: {limit: 0}, search: {field: comments, value: "ADM248D9B0260371FD2", operator: like}) {
    device_deploymentsFilter(pagina

In [49]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_18-07-2022_cumulus_31_33.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    logs=$(find "$dir_to_be_processed" -maxdepth 1 -name "logs_simex_move_files*.logs")
    echo "$logs"
    var=$(cat "$logs"|grep '248D9B0260371FD2' | head -n 1)
    if [ -z "$var" ]
    then
          echo "serial number not found"
    else
          cat "$logs"|head -n 50
    fi
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4283135/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4033497/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10307495/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/e

**There is a log which have audios that were taken in 175 days!!! why simex didn't produce a warning and thereby will not be moved**

## An adaptation to `move` cli will be implemented to take into account MAX_NUMBER_DAYS... now all files that appear in the logs will be moved backed to the dir original

Dir original:

```
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782/
```

Dir destiny:

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible
```

**First from `logs`**

```
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782/logs_simex_move_files_to_standard_directory.logs
```

**all files moved will be put in a txt**

In [26]:
%%bash
logs="/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782/logs_simex_move_files_to_standard_directory.logs"
grep "with name" "$logs"|cut -d':' -f4|cut -d' ' -f5 > "1_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt"

In [27]:
%%bash
head -n 10 "1_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt"

f08b1f1c4d0b7080cd9a3d7733fe72c1.WAV
a1c55497aa67e4d2207aa14538c630d3.WAV
52d6cfd3b505b055d3d531b45d3157f0.WAV
d0092feea5994e7ac03f96a1d0c8dd40.WAV
29b335c10eafc898bdb845419ad03f9e.WAV
c59bb1624cfcee9f46ec8627febbf0dd.WAV
38f7016298304eecf75198ef9e31e2e4.WAV
4384622d6301621234ba2c7a892bf08d.WAV
de75f810695b8ac24f460dbc262fdeac.WAV
61f7cb52b440d9d041ec2de08ce7eb93.WAV


In [28]:
%%bash
tail -n 10 "1_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt"

20ff09f7fab8823ccb9f5610a77772da.WAV
b71b88ccd7ae5c5b93b1a55d0565c3dd.WAV
ee36f80464404ed29ad53ff8e1017d83.WAV
995c81515757dd7341ca3760372409e7.WAV
ef724aa1a1de0f381438ad1ad7739dd5.WAV
c478d2ca9451fca71c89ae8d598a601a.WAV
8de06f99210ebcfde36741297c4f627a.WAV
5236ee91e2b35998311e0beb180fab5c.WAV
2c60fd43a166a208613728e35cf24ae1.WAV
b5cdb3f8d6daa8ee414986dd969a8116.WAV


In [29]:
%%bash
wc -l "1_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt"

10635 1_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt


**Include path where data is and create another .txt**

In [30]:
%%bash
path=/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible
for f in $(cat "1_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt")
    do
        echo "$path/$f" >> "2_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt"
    done

In [37]:
%%bash
head -n 10 "2_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt"

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/f08b1f1c4d0b7080cd9a3d7733fe72c1.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/a1c55497aa67e4d2207aa14538c630d3.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/52d6cfd3b505b055d3d531b45d3157f0.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/d0092feea5994e7ac03f96a1d0c8dd40.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/29b335c10eafc898bdb845419ad03f9e.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/c59bb1624cfcee9f46ec8627febbf0dd.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/38f7016298304eecf75198ef9e31e2e4.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/4384622d6301621234ba2c7a892bf08d.WAV
/LUSTRE/sacmod/S

In [38]:
%%bash
tail -n 10 "2_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt"

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/20ff09f7fab8823ccb9f5610a77772da.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/b71b88ccd7ae5c5b93b1a55d0565c3dd.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/ee36f80464404ed29ad53ff8e1017d83.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/995c81515757dd7341ca3760372409e7.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/ef724aa1a1de0f381438ad1ad7739dd5.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/c478d2ca9451fca71c89ae8d598a601a.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/8de06f99210ebcfde36741297c4f627a.WAV
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/5236ee91e2b35998311e0beb180fab5c.WAV
/LUSTRE/sacmod/S

In [36]:
%%bash
wc -l "2_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt"

10635 2_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt


**Each file from last txt will be moved to `/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782/`**

In [34]:
%%bash
dst_dir="/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782/"
for f in $(cat "2_audio_files_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt")
    do
    mv "$f" "$dst_dir"
done

**Lets check if there are repeated files in dir `/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/`**

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [3]:
patterns = ["WAV", "wav"]

In [4]:
d = "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/"

In [5]:
iterable = multiple_file_types(d,patterns, recursive=True)
l_not_repeated = []
l_repeated = []
l_not_repeated_check = []
l_repeated_check = []
for audio_file in iterable:
    audio_file_pathlib = pathlib.Path(audio_file)
    audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
    #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
    if audio_file_no_suffix not in l_not_repeated_check:
        l_not_repeated_check.append(audio_file_no_suffix)
        l_not_repeated.append(audio_file)
    else:
        l_repeated_check.append(audio_file_no_suffix)
        l_repeated.append(audio_file)

   

In [6]:
len(l_repeated)

1173

In [7]:
len(l_not_repeated)

3872

In [8]:
l_repeated[0:10]

['/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/42d8aa3b49eb0d43954ed044ef58fdfc.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/fcf6407b5833c183baf810915b81b183.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/cf56c803a3698677e815824094015086.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/4220711e3005214ddc83dee6d5d39c34.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/518eddf0cea44802260d79bd851cc5e6.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/aa24ceb9fb6264f5c44bb3771315a831.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/f03250ce70e35967643025e18876909d.wav',
 '/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/54b2d2f485390e5e56c5831

In [9]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/"
ls "$d"|grep "42d8aa3b49eb0d43954ed044ef58fdfc"

42d8aa3b49eb0d43954ed044ef58fdfc.WAV
42d8aa3b49eb0d43954ed044ef58fdfc.wav


**Checking that are the same audio**

In [14]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/"
cp "$d/42d8aa3b49eb0d43954ed044ef58fdfc.WAV" .
cp "$d/42d8aa3b49eb0d43954ed044ef58fdfc.wav" .

In [11]:
split_d = d.split("/")
cumulus = split_d[5]
nom_node = split_d[6]
num_serial = split_d[7]
date_dep = split_d[8]
filename_repeated = "".join(["/shared_volume/",
                             "repeated_audio_files_04-08-2022",
                             "_",
                             cumulus,
                             "_",
                             nom_node,
                             "_",
                             num_serial,
                             "_",
                             date_dep,
                             ".txt"])
print(filename_repeated)
with open(filename_repeated, 'a') as dst:
    for audio_file in l_repeated:
        dst.write(audio_file + "\n")
print("-"*40)

/shared_volume/repeated_audio_files_04-08-2022_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt
----------------------------------------


In [12]:
%%bash
wc -l /shared_volume/repeated_audio_files_04-08-2022_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt

1173 /shared_volume/repeated_audio_files_04-08-2022_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt


In [13]:
%%bash
head -n 5 /shared_volume/repeated_audio_files_04-08-2022_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/42d8aa3b49eb0d43954ed044ef58fdfc.wav
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/fcf6407b5833c183baf810915b81b183.wav
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/cf56c803a3698677e815824094015086.wav
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/4220711e3005214ddc83dee6d5d39c34.wav
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/518eddf0cea44802260d79bd851cc5e6.wav


**Move files in last txt**

In [14]:
%%bash
dst="/LUSTRE/sacmod/SIPECAM/sipecam_files_simex_error"
txt="/shared_volume/repeated_audio_files_04-08-2022_31_1_31_1_1213_248D9B0260371FD2_2022-02-22.txt"
for f in $(cat "$txt")
    do
        mv "$f" "$dst/"
done

In [15]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/"
ls "$d"|grep "42d8aa3b49eb0d43954ed044ef58fdfc"

42d8aa3b49eb0d43954ed044ef58fdfc.WAV


## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/
```

In [2]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 29,
    "MetadataDevice": {
        "Artist": "AudioMoth 248D9B0260371FD2",
        "SerialNumber": "248D9B0260371FD2",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.46268,
        "Longitude": -100.19501,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/4644f4c89d836f4aeef0527b7e262b55.wav": {
            "Battery": "4.6V",
            "Datetime": "20:40:00 25/02/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768

**Extract**

In [3]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [5]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/"
json=$(find "$d" -maxdepth 1 -name "*05-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/Audible_simex_metadata_files_and_device_05-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 248D9B0260371FD2",
        "SerialNumber": "248D9B0260371FD2",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.46268,
        "Longitude": -100.19501,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible/c150ffe29f2489608c43414d5c759011.WAV": {
            "Battery": "4.5V",
            "Datetime": "02:30:00 27/02/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.0 Kbit/sec",
            "SerialNumber

## For serial number: 24E1440360372FF8

**Check logs of `move`cli**

In [50]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_18-07-2022_cumulus_31_33.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    logs=$(find "$dir_to_be_processed" -maxdepth 1 -name "logs_simex_move_files*.logs")
    echo "$logs"
    var=$(cat "$logs"|grep '24E1440360372FF8' | head -n 1)
    if [ -z "$var" ]
    then
          echo "serial number not found"
    else
          cat "$logs"|head -n 50
    fi
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4283135/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4033497/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10307495/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/e

**Dates of deployment and coordinates of different directories are mapped to same dir**

```
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 25/logs_simex_move_files_to_standard_directory.logs

2022-02-22

2022-03-18

nom node: 1_31_1_1213, cum name: 31, date of depl: 2022-02-22, ecosystems name: Bosques templados,                          latitude and longitude of device:  17.47822, -100.23096, node category of integrity: Integro


----

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 30/logs_simex_move_files_to_standard_directory.logs


2022-02-22

2022-03-25

nom node: 1_31_1_1213, cum name: 31, date of depl: 2022-02-22, ecosystems name: Bosques templados,                          latitude and longitude of device:  17.47822, -100.23096, node category of integrity: Integro

----

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 21/logs_simex_move_files_to_standard_directory.logs

2022-02-22

2022-03-06

nom node: 1_31_1_1213, cum name: 31, date of depl: 2022-02-22, ecosystems name: Bosques templados,                          latitude and longitude of device:  17.47822, -100.23096, node category of integrity: Integro
```

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible
```

In [7]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 24,
    "MetadataDevice": {
        "Artist": "AudioMoth 24E1440360372FF8",
        "SerialNumber": "24E1440360372FF8",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.47822,
        "Longitude": -100.23096,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/0b740f35672e10a1ca0664c15486bce5.wav": {
            "Battery": "4.4V",
            "Datetime": "09:50:00 02/03/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768

**Extract**

In [9]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [10]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*05-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/Audible_simex_metadata_files_and_device_05-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24E1440360372FF8",
        "SerialNumber": "24E1440360372FF8",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.47822,
        "Longitude": -100.23096,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible/629d8e272ecc058cdf7c8301270918a5.wav": {
            "Battery": "4.2V",
            "Datetime": "21:20:00 15/03/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.0 Kbit/sec",
            "SerialNumber

## 24F3190160371FAB/2022-02-23

**Check logs of `move`cli**

In [22]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_18-07-2022_cumulus_31_33.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    logs=$(find "$dir_to_be_processed" -maxdepth 1 -name "logs_simex_move_files*.logs")
    echo "$logs"
    var=$(cat "$logs"|grep '24F3190160371FAB' | head -n 1)
    if [ -z "$var" ]
    then
          echo "serial number not found"
    else
          cat "$logs"|head -n 50
    fi
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/logs_simex_move_files_to_standard_directory.logs
2022-07-19 13:15:16,832 [INFO]  Dir /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644 has serial number 24F3190160371FAB
2022-07-19 13:15:16,834 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/20220406_125000.WAV has date 2022-04-06
2022-07-19 13:15:16,834 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/20220430_110000.WAV has date 2022-04-30
2022-07-19 13:15:16,834 [INFO]  DaysBetweenFirstAndLastDate: 24
2022-07-19 13:15:17,019 [INFO]  Query to Zendro GQL: query {
  physical_devices(pagination: {limit: 0}, search: {field: comments, value: "ADM24F3190160371FAB", operator: like}) {
    device_deploymentsFilter(pagination: {limit: 0}, search: {operator: and, search: [{field: date_deployment, value: "2022

**Dates of deployment and coordinates of different directories are mapped to same dir**

```

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 22/logs_simex_move_files_to_standard_directory.logs

2022-02-23

2022-03-09

nom node: 1_31_1_1213, cum name: 31, date of depl: 2022-02-23, ecosystems name: Bosques templados,                          latitude and longitude of device:  17.46504, -100.23405, node category of integrity: Integro

---

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 19/logs_simex_move_files_to_standard_directory.logs

2022-02-23

2022-03-01

nom node: 1_31_1_1213, cum name: 31, date of depl: 2022-02-23, ecosystems name: Bosques templados,                          latitude and longitude of device:  17.46504, -100.23405, node category of integrity: Integro


```

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible
```

In [12]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 6,
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371FAB",
        "SerialNumber": "24F3190160371FAB",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-23",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.46504,
        "Longitude": -100.23405,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/534576210bc0ce331e5f46493104356b.wav": {
            "Battery": "4.7V",
            "Datetime": "06:20:00 25/02/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.

**Extract**

In [13]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [14]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*05-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/Audible_simex_metadata_files_and_device_05-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371FAB",
        "SerialNumber": "24F3190160371FAB",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-23",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.46504,
        "Longitude": -100.23405,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible/f74c2437fa4e24a0979d2f809e04f456.wav": {
            "Battery": "4.8V",
            "Datetime": "22:20:00 23/02/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.0 Kbit/sec",
            "SerialNumber

## 24F3190160371FAB/2022-01-15/

**Check logs of `move`cli**

In [26]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_18-07-2022_cumulus_31_33.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    logs=$(find "$dir_to_be_processed" -maxdepth 1 -name "logs_simex_move_files*.logs")
    echo "$logs"
    var=$(cat "$logs"|grep '24F3190160371FAB' | head -n 1)
    if [ -z "$var" ]
    then
          echo "serial number not found"
    else
          cat "$logs"|head -n 50
    fi
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/logs_simex_move_files_to_standard_directory.logs
2022-07-19 13:15:16,832 [INFO]  Dir /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644 has serial number 24F3190160371FAB
2022-07-19 13:15:16,834 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/20220406_125000.WAV has date 2022-04-06
2022-07-19 13:15:16,834 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/20220430_110000.WAV has date 2022-04-30
2022-07-19 13:15:16,834 [INFO]  DaysBetweenFirstAndLastDate: 24
2022-07-19 13:15:17,019 [INFO]  Query to Zendro GQL: query {
  physical_devices(pagination: {limit: 0}, search: {field: comments, value: "ADM24F3190160371FAB", operator: like}) {
    device_deploymentsFilter(pagination: {limit: 0}, search: {operator: and, search: [{field: date_deployment, value: "2022

**Dates of deployment and coordinates of different directories are mapped to same dir**

```

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 134/logs_simex_move_files_to_standard_directory.logs

2022-01-15

2022-01-31

nom node: 1_31_0_1216, cum name: 31, date of depl: 2022-01-15, ecosystems name: Bosques templados,                          latitude and longitude of device:  17.39877, -100.26656, node category of integrity: Degradado

---

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 133/logs_simex_move_files_to_standard_directory.logs

2022-01-15

2022-01-25

nom node: 1_31_0_1216, cum name: 31, date of depl: 2022-01-15, ecosystems name: Bosques templados,                          latitude and longitude of device:  17.39877, -100.26656, node category of integrity: Degradado

---


/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 131/logs_simex_move_files_to_standard_directory.logs

2022-01-15

2022-01-20

node: 1_31_0_1216, cum name: 31, date of depl: 2022-01-15, ecosystems name: Bosques templados,                          latitude and longitude of device:  17.39877, -100.26656, node category of integrity: Degradado

---

```

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible
```

In [16]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 5,
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371FAB",
        "SerialNumber": "24F3190160371FAB",
        "NomenclatureNode": "1_31_0_1216",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-01-15",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.39877,
        "Longitude": -100.26656,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/3462f243784258ae309d7140d0ff19d9.wav": {
            "Battery": "4.1V",
            "Datetime": "11:40:00 20/01/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "76

**Extract**

In [17]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [18]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*05-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/Audible_simex_metadata_files_and_device_05-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371FAB",
        "SerialNumber": "24F3190160371FAB",
        "NomenclatureNode": "1_31_0_1216",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-01-15",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.39877,
        "Longitude": -100.26656,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible/8d75ba2b11e6ad2ce3b4a148ce97eb4c.wav": {
            "Battery": "4.0V",
            "Datetime": "21:40:00 27/01/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.0 Kbit/sec",
            "SerialNumb

## 248D9B0260371FD2/2021-11-06

**Check json of `move`cli**

In [6]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_18-07-2022_cumulus_31_33.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    logs=$(find "$dir_to_be_processed" -maxdepth 1 -name "logs_simex_move_files*.logs")
    echo "$logs"
    var=$(cat "$logs"|grep '248D9B0260371FD2' | head -n 1)
    if [ -z "$var" ]
    then
          echo "serial number not found"
    else
          cat "$logs"|head -n 70
    fi
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4283135/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4033497/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10307495/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/e

**Dates of deployment and coordinates of different directories are mapped to same dir**

```
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 84/logs_simex_move_files_to_standard_directory.logs


2021-11-18

2021-12-07


nom node: 1_31_0_1217, cum name: 31, date of depl: 2021-11-06, ecosystems name: Bosques templados,                                          latitude and longitude of device:  17.31268, -100.28287, node category of integrity: Degradado


---


/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 81/logs_simex_move_files_to_standard_directory.logs


2021-11-15

2021-11-26

nom node: 1_31_0_1217, cum name: 31, date of depl: 2021-11-06, ecosystems name: Bosques templados,                                          latitude and longitude of device:  17.31268, -100.28287, node category of integrity: Degradado

```

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico

```

In [20]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 11,
    "MetadataDevice": {
        "Artist": "AudioMoth 248D9B0260371FD2",
        "SerialNumber": "248D9B0260371FD2",
        "NomenclatureNode": "1_31_0_1217",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2021-11-06",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.31268,
        "Longitude": -100.28287,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/ba1f875f840c8c0dea9ebe601e4f7cba.wav": {
            "Battery": "4.6V",
            "Datetime": "23:20:00 15/11/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "

**Extract**

In [21]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [22]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*05-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_05-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 248D9B0260371FD2",
        "SerialNumber": "248D9B0260371FD2",
        "NomenclatureNode": "1_31_0_1217",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2021-11-06",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.31268,
        "Longitude": -100.28287,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico/cb3adafd3516f079825fa21f45a6bef0.wav": {
            "Battery": "4.5V",
            "Datetime": "04:20:00 26/11/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "6.1 Mbit/sec",
            "

# 24F31901603734A9/2021-11-06/

**Check json of `move`cli**

In [14]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_18-07-2022_cumulus_31_33.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    logs=$(find "$dir_to_be_processed" -maxdepth 1 -name "logs_simex_move_files*.logs")
    echo "$logs"
    var=$(cat "$logs"|grep '24F31901603734A9' | head -n 1)
    if [ -z "$var" ]
    then
          echo "serial number not found"
    else
          cat "$logs"|head -n 70
    fi
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4283135/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4033497/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10307495/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/e

**Dates of deployment and coordinates of different directories are mapped to same dir**

```
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 74/logs_simex_move_files_to_standard_directory.logs

2021-11-07

2021-11-22

nom node: 1_31_0_1217, cum name: 31, date of depl: 2021-11-06, ecosystems name: Bosques templados,                                          latitude and longitude of device:  17.31268, -100.28287, node category of integrity: Degradado


---

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 77/logs_simex_move_files_to_standard_directory.logs

2021-11-10

2021-12-02

nom node: 1_31_0_1217, cum name: 31, date of depl: 2021-11-06, ecosystems name: Bosques templados,                                          latitude and longitude of device:  17.31268, -100.28287, node category of integrity: Degradado

---

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Reconstructed labeled/Audio/wav/Group 79/logs_simex_move_files_to_standard_directory.logs

2021-11-12

2021-12-06

nom node: 1_31_0_1217, cum name: 31, date of depl: 2021-11-06, ecosystems name: Bosques templados,                                          latitude and longitude of device:  17.31268, -100.28287, node category of integrity: Degradado

---

```

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible

```

In [24]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 24,
    "MetadataDevice": {
        "Artist": "AudioMoth 24F31901603734A9",
        "SerialNumber": "24F31901603734A9",
        "NomenclatureNode": "1_31_0_1217",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2021-11-06",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.31268,
        "Longitude": -100.28287,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/ef8c9d78da78b09881f70c48b2837df7.wav": {
            "Battery": "4.1V",
            "Datetime": "01:10:00 05/12/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "7

**Extract**

In [25]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [26]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*05-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/Audible_simex_metadata_files_and_device_05-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24F31901603734A9",
        "SerialNumber": "24F31901603734A9",
        "NomenclatureNode": "1_31_0_1217",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2021-11-06",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.31268,
        "Longitude": -100.28287,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible/629b1a2a92548999f7dde9f1e144c56f.wav": {
            "Battery": "4.1V",
            "Datetime": "01:10:00 01/12/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.0 Kbit/sec",
            "SerialNumb

**Update dir /LUSTRE/sacmod/SIPECAM/data/files_moved_with_simex/ (delete all txt and create only one with all files)**

**Include in revision ipynb (the one I gave to Mariana) and in `directories_not_processed_by_simex` next dir:**

```
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782/logs_simex_move_files_to_standard_directory.logs
2022-07-19 13:44:55,146 [INFO]  Dir /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782 has serial number 248D9B0260371FD2
2022-07-19 13:44:55,147 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782/20211107_210000.WAV has date 2021-11-07
2022-07-19 13:44:55,147 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782/20220501_054000.WAV has date 2022-05-01
2022-07-19 13:44:55,147 [INFO]  DaysBetweenFirstAndLastDate: 175
2022-07-19 13:44:55,300 [INFO]  Query to Zendro GQL: query {
  physical_devices(pagination: {limit: 0}, search: {field: comments, value: "ADM248D9B0260371FD2", operator: like}) {
    device_deploymentsFilter(pagination: {limit: 0}, search: {operator: and, search: [{field: date_deployment, value: "2021-11-07", valueType: String, operator: gte}, {field: date_deployment, value: "2022-05-01", valueType: String, operator: lte}]}) {
      node {
        nomenclatura
        cat_integr
        ecosystems {
          name
        }
      }
      cumulus {
        name
        geometry
      }
      date_deployment
      latitude
      longitude
    }
  }
}
2022-07-19 13:44:55,300 [INFO]  SUCCESSFUL extraction of nomenclature of node, cumulus name and date of deployment
2022-07-19 13:44:55,300 [INFO]  directory /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782 has nom node: 1_31_1_1213, cum name: 31, date of depl: 2022-02-22, ecosystems name: Bosques templados,                          latitude and longitude of device:  17.46268, -100.19501, node category of integrity: Integro
2022-07-19 13:44:55,300 [INFO]  compute centroid of cumulus
2022-07-19 13:44:55,301 [INFO]  Centroid of cumulus, lat: 17.36169, long: -100.25274
2022-07-19 13:44:55,301 [INFO]  Validating lat and long of device are correct using lat long of cumulus centroid
2022-07-19 13:44:55,302 [INFO]  Latitude and Longitude of device are in cumulus geometry
2022-07-19 13:44:55,302 [INFO]  filling dict MetadataDevice using query results from Zendro
2022-07-19 13:44:55,302 [INFO]  path where files will be moved: /LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22
2022-07-19 13:44:55,415 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1008782/20220315_021000 2.WAV will be moved to: /LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible with name f08b1f1c4d0b7080cd9a3d7733fe72c1.WAV

```

In [ ]:


%%bash
echo "SIPECAM_ZENDRO_GQL_URL=https://gql.sipecamdata.conabio.gob.mx/" > ~/.simex_env
echo "SIPECAM_ZENDRO_GQL_USER=<user>" >> ~/.simex_env
echo "SIPECAM_ZENDRO_GQL_PASSWORD=<password>" >> ~/.simex_env



In [2]:
from simex.utils.zendro import query_for_move_files_to_standard_directory

In [3]:
first_date_str = "2021-11-07"
second_date_str = "2022-05-01"
serial_number = "248D9B0260371FD2"
file_type="audio"

In [4]:
query_result, operation_sgqlc = query_for_move_files_to_standard_directory(serial_number,
                                                                           first_date_str,
                                                                           second_date_str,
                                                                           file_type)

In [5]:
print(operation_sgqlc)

query {
  physical_devices(pagination: {limit: 0}, search: {field: comments, value: "ADM248D9B0260371FD2", operator: like}) {
    device_deploymentsFilter(pagination: {limit: 0}, search: {operator: and, search: [{field: date_deployment, value: "2021-11-07", valueType: String, operator: gte}, {field: date_deployment, value: "2022-05-01", valueType: String, operator: lte}]}) {
      node {
        nomenclatura
        cat_integr
        ecosystems {
          name
        }
      }
      cumulus {
        name
        geometry
      }
      date_deployment
      latitude
      longitude
    }
  }
}


In [6]:
device_deploymentsFilter_list = query_result["data"]["physical_devices"][0]["device_deploymentsFilter"]

In [7]:
device_deploymentsFilter_list

[{'node': {'nomenclatura': '1_31_1_1213',
   'cat_integr': 'Integro',
   'ecosystems': {'name': 'Bosques templados'}},
  'cumulus': {'name': '31',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-100.158838, 17.353264],
      [-100.17014, 17.425744],
      [-100.210284, 17.437271],
      [-100.402501, 17.340345],
      [-100.345016, 17.318128],
      [-100.182199, 17.305201],
      [-100.158838, 17.353264]]]}},
  'date_deployment': '2022-02-22T18:35:00.000Z',
  'latitude': 17.46268,
  'longitude': -100.19501}]

In [2]:
import datetime
from simex.utils.zendro import query_alternative_auxiliar_for_move_files_to_standard_directory, \
query_alternative_for_move_files_to_standard_directory

In [3]:

query_result, operation_sgqlc = query_alternative_auxiliar_for_move_files_to_standard_directory(serial_number,
                                                                                                file_type)
print(operation_sgqlc)
device_deploymentsFilter_list = query_result["data"]["physical_devices"][0]["device_deploymentsFilter"]
format_string_data = "%Y-%m-%d"
list_dates_device_deployment = [d["date_deployment"].split('T')[0] for d in device_deploymentsFilter_list]
list_datetimes_device_deployment = [datetime.datetime.strptime(d["date_deployment"].split('T')[0],
                                                               format_string_data) for d in device_deploymentsFilter_list]
first_datetime  = datetime.datetime.strptime(first_date_str, format_string_data)
second_datetime = datetime.datetime.strptime(second_date_str, format_string_data)

query {
  physical_devices(pagination: {limit: 0}, search: {field: comments, value: "ADMADM248D9B0260371FD2", operator: like}) {
    device_deploymentsFilter(pagination: {limit: 0}) {
      date_deployment
    }
  }
}


IndexError: list index out of range

**From last inspection dirs that `move` cli was successful**