# This notebook partially review [19-07-2022](https://github.com/CONABIO/sipecam-metadata-extractor/blob/develop/notebooks/history_SiPeCaM/4_07-2022/19-07-2022.ipynb) as next situation was found

## Here will search for files that have different serial number inside standard dir of cumulus 31 and 33 which are the ones that fell in this case when reviewing them... also this need to be checked for all directories in standard dir for all cumulus (but will not check this here)

**Reference txt's:**

```
/LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_17-07-2022.txt
/LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_18-07-2022.txt
/LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_19-07-2022.txt
/LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_20-07-2022.txt

```

**last only have images and videos from 31 and 33 cumulus**

In [21]:
%%bash
cat /LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_20-07-2022.txt

/LUSTRE/sacmod/SIPECAM/data/99/4_99_0_1579/24F319016037499D/2021-11-29/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/99/4_99_0_1579/242A260460371FDE/2021-11-29/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/99/4_99_0_1579/24F3190160377C0F/2021-11-29/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/99/4_99_0_1579/242A260460371EFA/2021-11-29/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/99/4_99_1_1577/24F31901603734DB/2021-11-27/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/99/4_99_1_1577/248D9B0260371EFA/2021-11-27/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/99/4_99_1_1577/248D9B0260371F52/2021-11-27/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/99/4_99_1_1577/24E1440360377AFD/2021-11-27/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/99/4_99_1_1581/HLPXGM09050041/2022-02-03/images_videos
/LUSTRE/sacmod/SIPECAM/data/99/4_99_1_1581/HLPXGM09050017/2022-02-03/images_videos
/LUSTRE/sacmod/SIPECAM/data/99/4_99_1_1581/HLPXGM09050017/2022-02-03/images_videos
/LUSTRE/sacmod/SIPECAM/data/99/4_99_1_1581/HLPX

## First txt audios

In [1]:
%%bash
cat /LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_17-07-2022.txt

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/HLPXGM09049998/2021-11-07/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09050019/2021-11-07/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09048869/2021-11-06/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09049878/2021-11-06/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09050016/2021-11-07/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09050019/2022-02-23/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09048869/2022-02-22/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049507/2022-02-22/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049878/2022-02-24/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09050016/2022-02-24/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/HLPXGM09049481/2022-01-15/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/HLPXGM09048325/2022-01-15/images_videos
/LUS

In [1]:
%%bash
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/24F3190160377B48/2021-10-31/audios/Audible" > /root/31_33_revision_17-07-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/248D9B0260372F15/2021-10-31/audios/Ultrasonico" >> /root/31_33_revision_17-07-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/24F31901603749F6/2021-11-01/audios/Ultrasonico" >> /root/31_33_revision_17-07-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/242A260460377B2F/2021-11-01/audios/Audible" >> /root/31_33_revision_17-07-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/242A2604603734A9/2021-11-02/audios/Ultrasonico" >> /root/31_33_revision_17-07-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/248D9B0260371EA1/2021-11-01/audios/Audible" >> /root/31_33_revision_17-07-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/248D9B0260377D10/2021-11-01/audios/Ultrasonico" >> /root/31_33_revision_17-07-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/24F3190160371ED3/2021-11-02/audios/Audible" >> /root/31_33_revision_17-07-2022.txt

In [2]:
%%bash
cat /root/31_33_revision_17-07-2022.txt

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/24F3190160377B48/2021-10-31/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/248D9B0260372F15/2021-10-31/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/24F31901603749F6/2021-11-01/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/242A260460377B2F/2021-11-01/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/242A2604603734A9/2021-11-02/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/248D9B0260371EA1/2021-11-01/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/248D9B0260377D10/2021-11-01/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/24F3190160371ED3/2021-11-02/audios/Audible


In [4]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat /root/31_33_revision_17-07-2022.txt)
    do echo "$dir_to_be_processed"
    s_n_r=$(echo "$dir_to_be_processed"|cut -d'/' -f8)
    echo "$s_n_r"
    check_if_files_in_dir_are_from_different_serial_numbers_and_move_them --input_directory "$dir_to_be_processed" --serial_number_reference "$s_n_r" --number_of_processes 10
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/24F3190160377B48/2021-10-31/audios/Audible
24F3190160377B48
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/248D9B0260372F15/2021-10-31/audios/Ultrasonico
248D9B0260372F15
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/24F31901603749F6/2021-11-01/audios/Ultrasonico
24F31901603749F6
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/242A260460377B2F/2021-11-01/audios/Audible
242A260460377B2F
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/242A2604603734A9/2021-11-02/audios/Ultrasonico
242A2604603734A9
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/248D9B0260371EA1/2021-11-01/audios/Audible
248D9B0260371EA1
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/248D9B0260377D10/2021-11-01/audios/Ultrasonico
248D9B0260377D10
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/24F3190160371ED3/2021-11-02/audios/Audible
24F3190160371ED3
----------------


In [5]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for d in $(cat /root/31_33_revision_17-07-2022.txt)
    do echo "$d"
    find "$d" -type d -name '*[0-9]*'
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/24F3190160377B48/2021-10-31/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/248D9B0260372F15/2021-10-31/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/24F31901603749F6/2021-11-01/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/242A260460377B2F/2021-11-01/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/242A2604603734A9/2021-11-02/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/248D9B0260371EA1/2021-11-01/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/248D9B0260377D10/2021-11-01/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/24F3190160371ED3/2021-11-02/audios/Audible
----------------


In [6]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for d in $(cat /root/31_33_revision_17-07-2022.txt)
    do echo "$d"
    find "$d" -type d -name '*new_dir*'
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/24F3190160377B48/2021-10-31/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/248D9B0260372F15/2021-10-31/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/24F31901603749F6/2021-11-01/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/242A260460377B2F/2021-11-01/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/242A2604603734A9/2021-11-02/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/248D9B0260371EA1/2021-11-01/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/248D9B0260377D10/2021-11-01/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/24F3190160371ED3/2021-11-02/audios/Audible
----------------


# Second txt audios

In [7]:
%%bash
cat /LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_18-07-2022.txt

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24F3190160377B16/2022-01-11/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/242A2604603734A9/2022-01-10/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260371EA1/2021-12-05/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/248D9B0260377D10/2022-01-11/audios/Ultrasonico


In [9]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat /LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_18-07-2022.txt)
    do echo "$dir_to_be_processed"
    s_n_r=$(echo "$dir_to_be_processed"|cut -d'/' -f8)
    echo "$s_n_r"
    check_if_files_in_dir_are_from_different_serial_numbers_and_move_them --input_directory "$dir_to_be_processed" --serial_number_reference "$s_n_r" --number_of_processes 10
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24F3190160377B16/2022-01-11/audios/Audible
24F3190160377B16
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/242A2604603734A9/2022-01-10/audios/Ultrasonico
242A2604603734A9
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260371EA1/2021-12-05/audios/Audible
248D9B0260371EA1
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible
24E1440360374A34
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/248D9B0260377D10/2022-01-11/audios/Ultrasonico
248D9B0260377D10
----------------


In [10]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for d in $(cat  /LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_18-07-2022.txt)
    do echo "$d"
    find "$d" -type d -name '*[0-9]*'
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24F3190160377B16/2022-01-11/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/242A2604603734A9/2022-01-10/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260371EA1/2021-12-05/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/248D9B0260377D10/2022-01-11/audios/Ultrasonico
----------------


In [11]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for d in $(cat /LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_18-07-2022.txt)
    do echo "$d"
    find "$d" -type d -name '*new_dir*'
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24F3190160377B16/2022-01-11/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/242A2604603734A9/2022-01-10/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260371EA1/2021-12-05/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/248D9B0260377D10/2022-01-11/audios/Ultrasonico
----------------


# 3d txt for audios

In [12]:
%%bash
cat /LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_19-07-2022.txt

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242

In [14]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat /LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_19-07-2022.txt)
    do echo "$dir_to_be_processed"
    s_n_r=$(echo "$dir_to_be_processed"|cut -d'/' -f8)
    echo "$s_n_r"
    check_if_files_in_dir_are_from_different_serial_numbers_and_move_them --input_directory "$dir_to_be_processed" --serial_number_reference "$s_n_r" --number_of_processes 10
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible
24F3190160377B16
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico
24F3190160377B48
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible
24E1440360374A34
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico
248D9B0260377D10
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible
248D9B0260371FD2
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible
24F3190160371F6C
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible
248D9B0260371F78
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible
248D9B0260371FD2
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1

**Check**

In [16]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for d in $(cat /LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_19-07-2022.txt)
    do echo "$d"
    find "$d" -type d -name '*new_dir*'
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/248D9B0260372F15_new_dir
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/24F31901603734A9_new_dir
----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24

**All the files that were created inside `*_new_dir` will be moved and recreate `jsons`**

**Move dirs that have serial number different from the std dir**

In [1]:
%%bash
mkdir -p /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/

In [2]:
%%bash
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/248D9B0260372F15_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/24F31901603734A9_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371F39_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F31901603734A9_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F3190160371F6C_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371FD2_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/24E1440360372FF8_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/242A260460373575_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/24F3190160371FAB_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible/24F3190160371FAB_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico/248D9B0260377D10_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico/242A2604603734A9_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico/24E1440360374A34_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico/248D9B0260371F39_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico/248D9B026037BD85_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico/248C7D075B1F35B9_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico/24E1440360371ED3_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico/24F3190160374A1B_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/248D9B0260371F39_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/248D9B026037BD85_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/24F31901603734A9_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/24F3190160371F6C_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/248D9B0260371FD2_new_dir" >> /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt



In [3]:
%%bash
cat  /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/248D9B0260372F15_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/24F31901603734A9_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371F39_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F31901603734A9_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F3190160371F6C_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371FD2_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/24E1440360372FF8_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/242A260460373575_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultras

In [5]:
%%bash
txt="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt"
dst_dir="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/"
for d in $(cat "$txt")
    do
        serial_number=$(echo $d|cut -d'/' -f12|cut -d'_' -f1)
        echo ""$dst_dir$serial_number""
        mkdir -p "$dst_dir$serial_number"
done

/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/248D9B0260372F15
/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/24F31901603734A9
/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/248D9B0260371F39
/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/24F31901603734A9
/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/24F3190160371F6C
/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/248D9B0260371FD2
/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/24E1440360372FF8
/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/242A260460373575
/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/24F3190160371FAB
/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/24F3190

In [17]:
%%bash
txt="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt"
dst_dir="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/"
for d in $(cat "$txt")
    do
        serial_number=$(echo $d|cut -d'/' -f12|cut -d'_' -f1)
        echo "files in $d"
        echo "will be moved to "$dst_dir$serial_number""
        for f in $(ls "$d")
            do
                mv "$d/$f" "$dst_dir$serial_number/"
            done
        echo "---------------"
done

files in /LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/248D9B0260372F15_new_dir
will be moved to /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/248D9B0260372F15
---------------
files in /LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/24F31901603734A9_new_dir
will be moved to /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/24F31901603734A9
---------------
files in /LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371F39_new_dir
will be moved to /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/248D9B0260371F39
---------------
files in /LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F31901603734A9_new_dir
will be moved to /LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/24F31

**Check if there are no wavs files**

In [6]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for d in $(cat /LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_19-07-2022.txt)
    do
    dirs_with_diff_serial_number=$(find "$d" -type d -name '*_new_dir*')
    for dir_diff in $dirs_with_diff_serial_number
        do
            echo "$dir_diff"
            ls "$dir_diff"|head -n 5
        done
    echo "----------------"
done
IFS=$SAVEIFS

----------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/248D9B0260372F15_new_dir
----------------
----------------
----------------
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/24F31901603734A9_new_dir
----------------
----------------
----------------
----------------
----------------
----------------
----------------
----------------
----------------
----------------
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371F39_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F31901603734A9_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F3190160371F6C_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371FD2_new_dir
----------------
----------------
--------

**Delete dirs with different serial numbers**

In [7]:
%%bash
txt="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt"
cat "$txt"

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/248D9B0260372F15_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/24F31901603734A9_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371F39_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F31901603734A9_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F3190160371F6C_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371FD2_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/24E1440360372FF8_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/242A260460373575_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultras

In [9]:
%%bash
txt="/LUSTRE/sacmod/SIPECAM/dirs_with_different_serial_numbers_detected_simex/06-08-2022/list_dirs_different_serial_number.txt"
for d in $(cat "$txt")
    do
        echo "$d"
        rm -rf "$d"
done

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/248D9B0260372F15_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/24F31901603734A9_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371F39_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F31901603734A9_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/24F3190160371F6C_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/248D9B0260371FD2_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/24E1440360372FF8_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/242A260460373575_new_dir
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultras

**Dirs that need to recreate jsons:**

In [2]:
%%bash
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico" >> /root/files_recreate_jsons_cumulus_31_33_06-08-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible" >> /root/files_recreate_jsons_cumulus_31_33_06-08-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico" >> /root/files_recreate_jsons_cumulus_31_33_06-08-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico" >> /root/files_recreate_jsons_cumulus_31_33_06-08-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible" >> /root/files_recreate_jsons_cumulus_31_33_06-08-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico" >> /root/files_recreate_jsons_cumulus_31_33_06-08-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico" >> /root/files_recreate_jsons_cumulus_31_33_06-08-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico" >> /root/files_recreate_jsons_cumulus_31_33_06-08-2022.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible" >> /root/files_recreate_jsons_cumulus_31_33_06-08-2022.txt



In [3]:
%%bash
cat /root/files_recreate_jsons_cumulus_31_33_06-08-2022.txt

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible


**For each of the last dirs check number of days and also if there are no repeated files**

# 24F3190160377B48/2021-12-04/

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [3]:
patterns = ["WAV", "wav"]

In [4]:
d = "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico"

In [5]:
iterable = multiple_file_types(d,patterns, recursive=True)
l_not_repeated = []
l_repeated = []
l_not_repeated_check = []
l_repeated_check = []
for audio_file in iterable:
    audio_file_pathlib = pathlib.Path(audio_file)
    audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
    #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
    if audio_file_no_suffix not in l_not_repeated_check:
        l_not_repeated_check.append(audio_file_no_suffix)
        l_not_repeated.append(audio_file)
    else:
        l_repeated_check.append(audio_file_no_suffix)
        l_repeated.append(audio_file)

   

In [6]:
len(l_repeated)

0

In [7]:
len(l_not_repeated)

1260

**Check json of `move`cli**

In [8]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_18-07-2022_cumulus_31_33.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    logs=$(find "$dir_to_be_processed" -maxdepth 1 -name "logs_simex_move_files*.logs")
    echo "$logs"
    var=$(cat "$logs"|grep '24F3190160377B48' | head -n 1)
    if [ -z "$var" ]
    then
          echo "serial number not found"
    else
          cat "$logs"|head -n 70
    fi
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4283135/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4033497/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/logs_simex_move_files_to_standard_directory.logs
2022-07-19 13:17:14,278 [INFO]  Dir /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349 has serial number 24F3190160377B48
2022-07-19 13:17:14,280 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/O

**74 Days but there were files that don't belong to this dir... let's regenerate it's json**

```
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/logs_simex_move_files_to_standard_directory.logs
2022-07-19 13:17:14,278 [INFO]  Dir /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349 has serial number 24F3190160377B48
2022-07-19 13:17:14,280 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/20211203_214000.WAV has date 2021-12-03
2022-07-19 13:17:14,280 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/20220215_032000.WAV has date 2022-02-15
2022-07-19 13:17:14,280 [INFO]  DaysBetweenFirstAndLastDate: 74
2022-07-19 13:17:14,441 [INFO]  Query to Zendro GQL: query {
  physical_devices(pagination: {limit: 0}, search: {field: comments, value: "ADM24F3190160377B48", operator: like}) {
    device_deploymentsFilter(pagination: {limit: 0}, search: {operator: and, search: [{field: date_deployment, value: "2021-12-03", valueType: String, operator: gte}, {field: date_deployment, value: "2022-02-15", valueType: String, operator: lte}]}) {
      node {
        nomenclatura
        cat_integr
        ecosystems {
          name
        }
      }
      cumulus {
        name
        geometry
      }
      date_deployment
      latitude
      longitude
    }
  }
}
2022-07-19 13:17:14,441 [INFO]  SUCCESSFUL extraction of nomenclature of node, cumulus name and date of deployment
2022-07-19 13:17:14,441 [INFO]  directory /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349 has nom node: 1_33_1_1222, cum name: 33, date of depl: 2021-12-04, ecosystems name: Bosques templados,                          latitude and longitude of device:  17.58421, -100.52076, node category of integrity: Integro
2022-07-19 13:17:14,441 [INFO]  compute centroid of cumulus
2022-07-19 13:17:14,442 [INFO]  Centroid of cumulus, lat: 17.57587, long: -100.64479
2022-07-19 13:17:14,442 [INFO]  Validating lat and long of device are correct using lat long of cumulus centroid
2022-07-19 13:17:14,443 [INFO]  Latitude and Longitude of device are in cumulus geometry
2022-07-19 13:17:14,443 [INFO]  filling dict MetadataDevice using query results from Zendro
2022-07-19 13:17:14,443 [INFO]  path where files will be moved: /LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04
2022-07-19 13:17:14,637 [INFO]  File /LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/20220120_190000.WAV will be moved to: /LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico with name c0a7c094d17764f90947ccd2764930ca.WAV

```

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico
```

In [9]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 74,
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160377B48",
        "SerialNumber": "24F3190160377B48",
        "NomenclatureNode": "1_33_1_1222",
        "CumulusName": "33",
        "CentroidCumulusLatitude": 17.57587,
        "CentroidCumulusLongitude": -100.64479,
        "DateDeployment": "2021-12-04",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.58421,
        "Longitude": -100.52076,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/c0a7c094d17764f90947ccd2764930ca.WAV": {
            "Battery": "3.8V",
            "Datetime": "19:00:00 20/01/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "Bi

**Extract**

In [10]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [11]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160377B48",
        "SerialNumber": "24F3190160377B48",
        "NomenclatureNode": "1_33_1_1222",
        "CumulusName": "33",
        "CentroidCumulusLatitude": 17.57587,
        "CentroidCumulusLongitude": -100.64479,
        "DateDeployment": "2021-12-04",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.58421,
        "Longitude": -100.52076,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/0c7a5e2c450100b80aaa13ac0d8825a3.WAV": {
            "Battery": "3.8V",
            "Datetime": "04:40:00 25/01/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "6.1 Mbit/sec",
            "Se

In [12]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|tail -n 10

/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
            "Latitude": 17.58421,
            "Longitude": -100.52076
        }
    },
    "FirstAndLastDate": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/25bee325308f787fb05c95b2569daee4.WAV": "2022-01-11",
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/24F3190160377B48/2021-12-04/audios/Ultrasonico/134a6ef3681fd9c303e39115d254299c.WAV": "2022-02-15"
    },
    "DaysBetweenFirstAndLastDate": 35
}


**35 days then it was ok at the end...**

# 24F3190160371F6C/2022-02-22

**Search for repetaed files**

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [3]:
patterns = ["WAV", "wav"]

In [4]:
d = "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible"

In [5]:
iterable = multiple_file_types(d,patterns, recursive=True)
l_not_repeated = []
l_repeated = []
l_not_repeated_check = []
l_repeated_check = []
for audio_file in iterable:
    audio_file_pathlib = pathlib.Path(audio_file)
    audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
    #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
    if audio_file_no_suffix not in l_not_repeated_check:
        l_not_repeated_check.append(audio_file_no_suffix)
        l_not_repeated.append(audio_file)
    else:
        l_repeated_check.append(audio_file_no_suffix)
        l_repeated.append(audio_file)

   

In [6]:
len(l_repeated)

0

In [7]:
len(l_not_repeated)

2047

**Check json of `move`cli**

In [8]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_18-07-2022_cumulus_31_33.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    logs=$(find "$dir_to_be_processed" -maxdepth 1 -name "logs_simex_move_files*.logs")
    echo "$logs"
    var=$(cat "$logs"|grep '24F3190160371F6C' | head -n 1)
    if [ -z "$var" ]
    then
          echo "serial number not found"
    else
          cat "$logs"|head -n 70
    fi
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4283135/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4033497/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10307495/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/e

**147 Days but there were files that don't belong to this dir... let's regenerate it's json**

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible
```

In [9]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 147,
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371F6C",
        "SerialNumber": "24F3190160371F6C",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.46268,
        "Longitude": -100.19501,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/7eba8d928c3c85c17a153a0f814d03b4.WAV": {
            "Battery": "4.5V",
            "Datetime": "15:10:00 10/11/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "76

**Extract**

In [10]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [12]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/Audible_simex_metadata_files_and_device_06-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371F6C",
        "SerialNumber": "24F3190160371F6C",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.46268,
        "Longitude": -100.19501,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/04bbbd68baf8d90067fae3526efeddfc.WAV": {
            "Battery": "4.4V",
            "Datetime": "13:40:00 18/11/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.0 Kbit/sec",
            "SerialNumber

In [13]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|tail -n 10

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/Audible_simex_metadata_files_and_device_06-08-2022.json
            "Latitude": 17.46268,
            "Longitude": -100.19501
        }
    },
    "FirstAndLastDate": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/28a519417984b2c817eb399915cf5cae.WAV": "2021-11-07",
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Audible/7ac826499f6ecc24036ae5a33f35eacd.WAV": "2021-11-21"
    },
    "DaysBetweenFirstAndLastDate": 14
}


**14 days then it was ok at the end...**

# 248D9B026037BD85/2021-11-07/

**Search for repetaed files**

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [3]:
patterns = ["WAV", "wav"]

In [4]:
d = "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico"

In [5]:
iterable = multiple_file_types(d,patterns, recursive=True)
l_not_repeated = []
l_repeated = []
l_not_repeated_check = []
l_repeated_check = []
for audio_file in iterable:
    audio_file_pathlib = pathlib.Path(audio_file)
    audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
    #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
    if audio_file_no_suffix not in l_not_repeated_check:
        l_not_repeated_check.append(audio_file_no_suffix)
        l_not_repeated.append(audio_file)
    else:
        l_repeated_check.append(audio_file_no_suffix)
        l_repeated.append(audio_file)

   

In [6]:
len(l_repeated)

0

In [7]:
len(l_not_repeated)

62

**Check json of `move`cli**

In [8]:
%%bash
list_of_dirs_to_be_processed=/shared_volume/sipecam_subdirectories_18-07-2022_cumulus_31_33.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    logs=$(find "$dir_to_be_processed" -maxdepth 1 -name "logs_simex_move_files*.logs")
    echo "$logs"
    var=$(cat "$logs"|grep '248D9B026037BD85' | head -n 1)
    if [ -z "$var" ]
    then
          echo "serial number not found"
    else
          cat "$logs"|head -n 70
    fi
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost1611644/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4283135/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost4033497/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10305349/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/entrega.09.Junio.2022/Cumulos_33_y_31/RESPALDO/Orphans/Lost461305/10307495/logs_simex_move_files_to_standard_directory.logs
serial number not found
----------------------------
/LUSTRE/sacmod/SIPECAM/e

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico
```

In [9]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 19,
    "MetadataDevice": {
        "Artist": "AudioMoth 248D9B026037BD85",
        "SerialNumber": "248D9B026037BD85",
        "NomenclatureNode": "1_31_0_1217",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2021-11-07",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.3094,
        "Longitude": -100.28818,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/ab43188a1dc09abe9b20ed2c156edfc0.wav": {
            "Battery": "4.6V",
            "Datetime": "00:00:00 10/11/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "B

**Extract**

In [10]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [11]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 248D9B026037BD85",
        "SerialNumber": "248D9B026037BD85",
        "NomenclatureNode": "1_31_0_1217",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2021-11-07",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.3094,
        "Longitude": -100.28818,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/dd66df78a9785ad8682c5737a67cccb6.wav": {
            "Battery": "4.7V",
            "Datetime": "19:40:00 08/11/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "6.1 Mbit/sec",
            "S

In [12]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|tail -n 10

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
            "Latitude": 17.3094,
            "Longitude": -100.28818
        }
    },
    "FirstAndLastDate": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/dd66df78a9785ad8682c5737a67cccb6.wav": "2021-11-08",
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B026037BD85/2021-11-07/audios/Ultrasonico/6d96d716f1cf3a03325a6a0a682202a8.wav": "2021-11-10"
    },
    "DaysBetweenFirstAndLastDate": 2
}


# 24E1440360371ED3/2022-02-22

**Search for repetaed files**

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [3]:
patterns = ["WAV", "wav"]

In [4]:
d = "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico"

In [5]:
iterable = multiple_file_types(d,patterns, recursive=True)
l_not_repeated = []
l_repeated = []
l_not_repeated_check = []
l_repeated_check = []
for audio_file in iterable:
    audio_file_pathlib = pathlib.Path(audio_file)
    audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
    #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
    if audio_file_no_suffix not in l_not_repeated_check:
        l_not_repeated_check.append(audio_file_no_suffix)
        l_not_repeated.append(audio_file)
    else:
        l_repeated_check.append(audio_file_no_suffix)
        l_repeated.append(audio_file)

   

In [6]:
len(l_repeated)

0

In [7]:
len(l_not_repeated)

196

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico
```

In [8]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 18,
    "MetadataDevice": {
        "Artist": "AudioMoth 24E1440360371ED3",
        "SerialNumber": "24E1440360371ED3",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.47822,
        "Longitude": -100.23096,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/e428ff1d3795f28effe5f47a3537b81f.wav": {
            "Battery": "4.4V",
            "Datetime": "23:00:00 05/03/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "Bi

**Extract**

In [9]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [10]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24E1440360371ED3",
        "SerialNumber": "24E1440360371ED3",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.47822,
        "Longitude": -100.23096,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/ea283232dc2376b4a5f230e9967eea82.wav": {
            "Battery": "4.4V",
            "Datetime": "22:40:00 06/03/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "6.1 Mbit/sec",
            "Se

In [11]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|tail -n 10

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
            "Latitude": 17.47822,
            "Longitude": -100.23096
        }
    },
    "FirstAndLastDate": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/d95b774259eb60fb861e5f7c4778470f.wav": "2022-03-03",
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360371ED3/2022-02-22/audios/Ultrasonico/24171d539e646f2b45e22b17fa90e38a.wav": "2022-03-08"
    },
    "DaysBetweenFirstAndLastDate": 5
}


# 24E1440360371ED3/2022-01-15

**Search for repetaed files**

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [3]:
patterns = ["WAV", "wav"]

In [4]:
d = "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible"

In [5]:
iterable = multiple_file_types(d,patterns, recursive=True)
l_not_repeated = []
l_repeated = []
l_not_repeated_check = []
l_repeated_check = []
for audio_file in iterable:
    audio_file_pathlib = pathlib.Path(audio_file)
    audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
    #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
    if audio_file_no_suffix not in l_not_repeated_check:
        l_not_repeated_check.append(audio_file_no_suffix)
        l_not_repeated.append(audio_file)
    else:
        l_repeated_check.append(audio_file_no_suffix)
        l_repeated.append(audio_file)

   

In [6]:
len(l_repeated)

0

In [7]:
len(l_not_repeated)

4

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible
```

In [8]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 1,
    "MetadataDevice": {
        "Artist": "AudioMoth 24E1440360371ED3",
        "SerialNumber": "24E1440360371ED3",
        "NomenclatureNode": "1_31_0_1216",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-01-15",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.39541,
        "Longitude": -100.28399,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible/4a76bc68034ad17e1e7bd139d8223731.wav": {
            "Battery": "3.2V",
            "Datetime": "12:20:00 20/01/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "76

**Extract**

In [9]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [10]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible/Audible_simex_metadata_files_and_device_06-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24E1440360371ED3",
        "SerialNumber": "24E1440360371ED3",
        "NomenclatureNode": "1_31_0_1216",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-01-15",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.39541,
        "Longitude": -100.28399,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible/6fa31d750e539129409424d1728759e2.wav": {
            "Battery": "3.2V",
            "Datetime": "12:00:00 20/01/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.0 Kbit/sec",
            "SerialNumb

In [11]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|tail -n 10

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible/Audible_simex_metadata_files_and_device_06-08-2022.json
            "Latitude": 17.39541,
            "Longitude": -100.28399
        }
    },
    "FirstAndLastDate": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible/6fa31d750e539129409424d1728759e2.wav": "2022-01-20",
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24E1440360371ED3/2022-01-15/audios/Audible/bfcab003dfd622635ca2f086f870f6a9.wav": "2022-01-20"
    },
    "DaysBetweenFirstAndLastDate": 1
}


# 24F3190160371ED3/2022-02-17

**Search for repetaed files**

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [3]:
patterns = ["WAV", "wav"]

In [4]:
d = "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico"

In [5]:
iterable = multiple_file_types(d,patterns, recursive=True)
l_not_repeated = []
l_repeated = []
l_not_repeated_check = []
l_repeated_check = []
for audio_file in iterable:
    audio_file_pathlib = pathlib.Path(audio_file)
    audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
    #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
    if audio_file_no_suffix not in l_not_repeated_check:
        l_not_repeated_check.append(audio_file_no_suffix)
        l_not_repeated.append(audio_file)
    else:
        l_repeated_check.append(audio_file_no_suffix)
        l_repeated.append(audio_file)

   

In [6]:
len(l_repeated)

0

In [7]:
len(l_not_repeated)

112

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico
```

In [8]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 18,
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371ED3",
        "SerialNumber": "24F3190160371ED3",
        "NomenclatureNode": "1_33_0_1226",
        "CumulusName": "33",
        "CentroidCumulusLatitude": 17.57587,
        "CentroidCumulusLongitude": -100.64479,
        "DateDeployment": "2022-02-17",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.62713,
        "Longitude": -100.68359,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico/2153e8d935f2039c7ca168b740714f90.wav": {
            "Battery": "4.3V",
            "Datetime": "00:00:00 28/03/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "

**Extract**

In [9]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [10]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371ED3",
        "SerialNumber": "24F3190160371ED3",
        "NomenclatureNode": "1_33_0_1226",
        "CumulusName": "33",
        "CentroidCumulusLatitude": 17.57587,
        "CentroidCumulusLongitude": -100.64479,
        "DateDeployment": "2022-02-17",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.62713,
        "Longitude": -100.68359,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico/94fb72e357e5c54cec270f601f79a55b.wav": {
            "Battery": "4.3V",
            "Datetime": "21:40:00 27/03/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "6.1 Mbit/sec",
            "

In [11]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|tail -n 10

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
            "Latitude": 17.62713,
            "Longitude": -100.68359
        }
    },
    "FirstAndLastDate": {
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico/8a022887a81e81d0ec773fd28f297707.wav": "2022-03-25",
        "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160371ED3/2022-02-17/audios/Ultrasonico/6266123186a43007acf25199bd97e10d.wav": "2022-03-28"
    },
    "DaysBetweenFirstAndLastDate": 3
}


# /LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico

**Search for repetaed files**

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [3]:
patterns = ["WAV", "wav"]

In [4]:
d = "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico"

In [5]:
iterable = multiple_file_types(d,patterns, recursive=True)
l_not_repeated = []
l_repeated = []
l_not_repeated_check = []
l_repeated_check = []
for audio_file in iterable:
    audio_file_pathlib = pathlib.Path(audio_file)
    audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
    #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
    if audio_file_no_suffix not in l_not_repeated_check:
        l_not_repeated_check.append(audio_file_no_suffix)
        l_not_repeated.append(audio_file)
    else:
        l_repeated_check.append(audio_file_no_suffix)
        l_repeated.append(audio_file)

   

In [6]:
len(l_repeated)

0

In [7]:
len(l_not_repeated)

433

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico
```

In [8]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 14,
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371F6C",
        "SerialNumber": "24F3190160371F6C",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.46268,
        "Longitude": -100.19501,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico/7ab272b7a98b80dbe190bfac6e63d900.wav": {
            "Battery": "4.4V",
            "Datetime": "05:00:00 08/03/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "Bi

**Extract**

In [9]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [10]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371F6C",
        "SerialNumber": "24F3190160371F6C",
        "NomenclatureNode": "1_31_1_1213",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2022-02-22",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.46268,
        "Longitude": -100.19501,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico/3de5895de309bee21499d777ceec0231.wav": {
            "Battery": "4.5V",
            "Datetime": "20:20:00 07/03/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "6.1 Mbit/sec",
            "Se

In [11]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|tail -n 10

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
            "Latitude": 17.46268,
            "Longitude": -100.19501
        }
    },
    "FirstAndLastDate": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico/c58ffbf1ee78e67efe66ff685384b4fc.wav": "2022-02-25",
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371F6C/2022-02-22/audios/Ultrasonico/f8d6f92e0fd1b66c263a25e3045f911e.wav": "2022-03-09"
    },
    "DaysBetweenFirstAndLastDate": 12
}


# /LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico

**Search for repetaed files**

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [3]:
patterns = ["WAV", "wav"]

In [4]:
d = "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico"

In [5]:
iterable = multiple_file_types(d,patterns, recursive=True)
l_not_repeated = []
l_repeated = []
l_not_repeated_check = []
l_repeated_check = []
for audio_file in iterable:
    audio_file_pathlib = pathlib.Path(audio_file)
    audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
    #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
    if audio_file_no_suffix not in l_not_repeated_check:
        l_not_repeated_check.append(audio_file_no_suffix)
        l_not_repeated.append(audio_file)
    else:
        l_repeated_check.append(audio_file_no_suffix)
        l_repeated.append(audio_file)

   

In [6]:
len(l_repeated)

0

In [7]:
len(l_not_repeated)

369

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico
```

In [8]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 18,
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371FAB",
        "SerialNumber": "24F3190160371FAB",
        "NomenclatureNode": "1_31_1_1209",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2021-12-12",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.32408,
        "Longitude": -100.15482,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico/b335b05d4c69523701e5bc92eaf935e3.wav": {
            "Battery": "4.3V",
            "Datetime": "03:00:00 27/12/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "Bi

**Extract**

In [9]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [10]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24F3190160371FAB",
        "SerialNumber": "24F3190160371FAB",
        "NomenclatureNode": "1_31_1_1209",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2021-12-12",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.32408,
        "Longitude": -100.15482,
        "NodeCategoryIntegrity": "Integro"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico/20603a2cb9fa806913ab8d08280cc023.wav": {
            "Battery": "4.2V",
            "Datetime": "00:00:00 01/01/2022 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "6.1 Mbit/sec",
            "Se

In [11]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|tail -n 10

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_06-08-2022.json
            "Latitude": 17.32408,
            "Longitude": -100.15482
        }
    },
    "FirstAndLastDate": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico/845942f3e7b94276df0a38cc15f5abb2.wav": "2021-12-26",
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/24F3190160371FAB/2021-12-12/audios/Ultrasonico/7b9bc05dc1b8652424378d334d48ff70.wav": "2022-01-06"
    },
    "DaysBetweenFirstAndLastDate": 11
}


# /LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible

**Search for repetaed files**

In [1]:
import os
import glob
import itertools
import pathlib

In [2]:
def multiple_file_types(input_directory, patterns, recursive=False):
    """
    Return iterable with files that have a common pattern. Will search
    in a recursive or non recursive way.
    Args:
        input_directory (str): directory where files with common pattern
        will be searched.
        patterns (list): list of patterns to search for.
    Returns:
        iterable with files that have a common pattern.
    """
    if recursive:
        expression = "/**/*"
    else:
        expression = "/*"
    return itertools.chain.from_iterable(glob.iglob(input_directory + \
                                                    expression + pattern,
                                                    recursive=recursive) for pattern in patterns)

In [3]:
patterns = ["WAV", "wav"]

In [4]:
d = "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible"

In [5]:
iterable = multiple_file_types(d,patterns, recursive=True)
l_not_repeated = []
l_repeated = []
l_not_repeated_check = []
l_repeated_check = []
for audio_file in iterable:
    audio_file_pathlib = pathlib.Path(audio_file)
    audio_file_no_suffix = audio_file.split(audio_file_pathlib.suffix)[0]
    #audio_filename = audio_file_pathlib.name.split(audio_file_pathlib.suffix)[0]
    if audio_file_no_suffix not in l_not_repeated_check:
        l_not_repeated_check.append(audio_file_no_suffix)
        l_not_repeated.append(audio_file)
    else:
        l_repeated_check.append(audio_file_no_suffix)
        l_repeated.append(audio_file)

   

In [6]:
len(l_repeated)

0

In [7]:
len(l_not_repeated)

349

## Rerun `extract` with hardcoding info

**Check `json` under dir:**

```
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible
```

In [8]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
{
    "DaysBetweenFirstAndLastDate": 23,
    "MetadataDevice": {
        "Artist": "AudioMoth 24E1440360371F6C",
        "SerialNumber": "24E1440360371F6C",
        "NomenclatureNode": "1_31_0_1217",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2021-11-07",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.3094,
        "Longitude": -100.28818,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/2a2e014a8f54ecb78dcf8c96a42d88e4.wav": {
            "Battery": "4.4V",
            "Datetime": "13:20:00 09/11/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "76

**Extract**

In [9]:
%%bash
dir_to_be_processed="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible"
extract_serial_numbers_dates_and_metadata_of_files_and_device --input_dir "$dir_to_be_processed" --number_of_processes 12

**Check**

In [10]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|head -n 60

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/Audible_simex_metadata_files_and_device_06-08-2022.json
{
    "MetadataDevice": {
        "Artist": "AudioMoth 24E1440360371F6C",
        "SerialNumber": "24E1440360371F6C",
        "NomenclatureNode": "1_31_0_1217",
        "CumulusName": "31",
        "CentroidCumulusLatitude": 17.36169,
        "CentroidCumulusLongitude": -100.25274,
        "DateDeployment": "2021-11-07",
        "EcosystemsName": "Bosques templados",
        "Latitude": 17.3094,
        "Longitude": -100.28818,
        "NodeCategoryIntegrity": "Degradado"
    },
    "MetadataFiles": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/3893940589159272204874fabb383059.wav": {
            "Battery": "4.7V",
            "Datetime": "23:40:00 07/11/2021 (UTC-0600)",
            "Gain": "medium",
            "Timezone": "UTC",
            "BitRate": "768.0 Kbit/sec",
            "SerialNumbe

In [11]:
%%bash
d="/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible"
json=$(find "$d" -maxdepth 1 -name "*06-08-2022.json")
echo "$json"
python3 -mjson.tool "$json"|tail -n 10

/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/Audible_simex_metadata_files_and_device_06-08-2022.json
            "Latitude": 17.3094,
            "Longitude": -100.28818
        }
    },
    "FirstAndLastDate": {
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/3893940589159272204874fabb383059.wav": "2021-11-07",
        "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24E1440360371F6C/2021-11-07/audios/Audible/b2315dc82ec12a6efd366c76dbb2a901.wav": "2021-11-10"
    },
    "DaysBetweenFirstAndLastDate": 3
}


# For all directories that didn't have files with different serial number, check their jsons in the DaysBetweenFirstAndLastDate to see if there's nothing wrong (for example having large number of days)

In [14]:
%%bash
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/audios/Ultrasonico" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/audios/Ultrasonico" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/24F3190160377B16/2021-12-05/audios/Ultrasonico" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/24F31901603734A9/2021-11-06/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260371F78/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/24F3190160371FAB/2022-01-15/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/248D9B0260372F15/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/242A2604603734A9/2021-12-04/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/248D9B0260371FD2/2021-11-06/audios/Ultrasonico" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/248D9B0260371F78/2022-02-19/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/audios/Ultrasonico" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24E1440360372FF8/2022-02-22/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/24F3190160371FAB/2022-02-23/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/24E1440360371ED3/2021-12-12/audios/Audible" >> /root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt


In [18]:
%%bash
list_of_dirs_to_be_processed=/root/list_31_33_that_were_moved_and_files_are_correct_inside_dirs.txt
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat $list_of_dirs_to_be_processed)
    do
    echo "$dir_to_be_processed"
    json=$(find "$dir_to_be_processed" -maxdepth 1 -name "*19-07-2022*.json")
    echo "$json"
    python3 -mjson.tool "$json" | grep "DaysBetweenFirstAndLastDate"
    echo "----------------------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/24F3190160377B16/2022-02-17/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
    "DaysBetweenFirstAndLastDate": 11,
----------------------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/Audible_simex_metadata_files_and_device_19-07-2022.json
    "DaysBetweenFirstAndLastDate": 141,
----------------------------
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico
/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/248D9B0260377D10/2021-12-04/audios/Ultrasonico/Ultrasonico_simex_metadata_files_and_device_19-07-2022.json
    "DaysBetweenFirstAndLastDate": 8,
----------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/248D9B0260371FD2/2022-02-22/audios/Audible
/LUSTRE/sacmod

**For the ones that are greater than 60 days let's check if they have been processed in [10_fill_metadata_json_for_audios_and_image](https://github.com/CONABIO/sipecam-metadata-extractor/blob/develop/notebooks/history_SiPeCaM/10_fill_metadata_json_for_audios_and_images.ipynb)**

In [19]:
%%bash
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/audios/Ultrasonico" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/24F3190160377B48/2022-02-19/audios/Ultrasonico" >> /root/files_with_larger_daysbetweenfirstandlastdate.txt

In [20]:
%%bash
for dir_to_be_processed in $(cat /root/files_with_larger_daysbetweenfirstandlastdate.txt)
    do
    json=$(find "$dir_to_be_processed" -maxdepth 1 -name "*08-2022*.json")
    echo "$json"
    python3 -mjson.tool "$json" | grep "DaysBetweenFirstAndLastDate"
    echo "----------------------------"
done

/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/24E1440360374A34/2022-01-10/audios/Audible/Audible_simex_metadata_files_and_device_06-08-2022.json
    "DaysBetweenFirstAndLastDate": 46
----------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/Audible_simex_metadata_files_and_device_05-08-2022.json
    "DaysBetweenFirstAndLastDate": 44
----------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/Audible_simex_metadata_files_and_device_05-08-2022.json
    "DaysBetweenFirstAndLastDate": 44
----------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/Audible_simex_metadata_files_and_device_05-08-2022.json
    "DaysBetweenFirstAndLastDate": 44
----------------------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/242A260460373575/2021-12-12/audios/Audible/Audible_simex_metadata_files_and_device_05-08-2022.json
    "DaysBetweenFirstA

**Then they have been fixed**

# For all the images_videos dirs let's check if all the files are under their correct dirs

**Reference txt's:**

```
/LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_17-07-2022.txt
/LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_18-07-2022.txt
/LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_19-07-2022.txt
/LUSTRE/sacmod/SIPECAM/data/dirs_moved_with_simex/dirs_moved_with_simex_20-07-2022.txt

```

In [22]:
%%bash
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/HLPXGM09049998/2021-11-07/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09050019/2021-11-07/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09048869/2021-11-06/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09049878/2021-11-06/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09050016/2021-11-07/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09050019/2022-02-23/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09048869/2022-02-22/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049507/2022-02-22/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049878/2022-02-24/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09050016/2022-02-24/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/HLPXGM09049481/2022-01-15/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/HLPXGM09048325/2022-01-15/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/HLPXGM09049998/2022-01-15/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/HLPXGM09049997/2022-01-15/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/HLPXGM09049616/2022-01-16/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1209/HLPXGM09049481/2021-12-09/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/HLPXGM09048325/2021-12-09/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/HLPXGM09049998/2021-12-09/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/HLPXGM09049997/2021-12-09/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/HLPXGM09049616/2021-12-09/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049481/2022-02-22/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049997/2022-02-23/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09048325/2022-02-22/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/HLPXGM09049970/2021-10-31/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/HLPXGM09049337/2021-10-31/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/HLPXGM09048227/2021-10-31/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/HLPXGM09048870/2021-11-01/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1225/HLPXGM09049899/2021-10-31/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/HLPXGM09048870/2022-02-19/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/HLPXGM09048227/2022-02-17/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/HLPXGM09049337/2022-02-17/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/HLPXGM09049102/2022-01-10/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/HLPXGM09048398/2022-01-10/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/HLPXGM09048461/2022-01-11/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1224/HLPXGM09049898/2022-01-11/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/HLPXGM09049102/2021-11-01/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/HLPXGM09048398/2021-11-01/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/HLPXGM09048461/2021-11-02/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/HLPXGM09048463/2021-11-01/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/HLPXGM09049898/2021-11-01/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/HLPXGM09049102/2022-02-17/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/HLPXGM09048398/2022-02-16/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1226/HLPXGM09048463/2022-02-17/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049970/2021-12-03/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049337/2021-12-02/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09048227/2021-12-04/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09048870/2021-12-03/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1222/HLPXGM09049899/2021-12-03/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/HLPXGM09048463/2021-12-05/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1227/HLPXGM09049102/2021-12-04/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/HLPXGM09048461/2021-12-04/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/HLPXGM09049898/2021-12-03/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_0_1223/HLPXGM09048398/2021-12-03/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09049507/2021-11-08/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt
echo "/LUSTRE/sacmod/SIPECAM/data/33/1_33_1_1219/HLPXGM09049899/2022-02-18/images_videos" >> /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt

In [23]:
%%bash
cat /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/HLPXGM09049998/2021-11-07/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09050019/2021-11-07/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09048869/2021-11-06/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09049878/2021-11-06/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09050016/2021-11-07/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09050019/2022-02-23/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09048869/2022-02-22/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049507/2022-02-22/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049878/2022-02-24/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09050016/2022-02-24/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/HLPXGM09049481/2022-01-15/images_videos
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1216/HLPXGM09048325/2022-01-15/images_videos
/LUS

In [2]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for dir_to_be_processed in $(cat /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt)
    do echo "$dir_to_be_processed"
    s_n_r=$(echo "$dir_to_be_processed"|cut -d'/' -f8)
    echo "$s_n_r"
    check_if_files_in_dir_are_from_different_serial_numbers_and_move_them --input_directory "$dir_to_be_processed" --serial_number_reference "$s_n_r" --number_of_processes 10
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/HLPXGM09049998/2021-11-07/images_videos
HLPXGM09049998
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09050019/2021-11-07/images_videos
HLPXGM09050019
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09048869/2021-11-06/images_videos
HLPXGM09048869
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09049878/2021-11-06/images_videos
HLPXGM09049878
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09050016/2021-11-07/images_videos
HLPXGM09050016
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09050019/2022-02-23/images_videos
HLPXGM09050019
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09048869/2022-02-22/images_videos
HLPXGM09048869
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049507/2022-02-22/images_videos
HLPXGM09049507
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049878/2022-02-24/images_vide

In [3]:
%%bash
SAVEIFS=$IFS;IFS=$(echo -en "\n\b")
for d in $(cat /root/list_31_33_images_videos_to_check_if_files_are_in_correct_dirs.txt)
    do echo "$d"
    find "$d" -type d -name '*new_dir*'
    echo "----------------"
done
IFS=$SAVEIFS

/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1211/HLPXGM09049998/2021-11-07/images_videos
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09050019/2021-11-07/images_videos
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09048869/2021-11-06/images_videos
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09049878/2021-11-06/images_videos
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_0_1217/HLPXGM09050016/2021-11-07/images_videos
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09050019/2022-02-23/images_videos
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09048869/2022-02-22/images_videos
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049507/2022-02-22/images_videos
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09049878/2022-02-24/images_videos
----------------
/LUSTRE/sacmod/SIPECAM/data/31/1_31_1_1213/HLPXGM09050016/2022-02-24/images_videos
----------------
